  {
    user:"fisica.conceitual", av:"∴", avc:"#0a84ff", disp:"Cap. 1 — Sobre a Ciência",
    time:"há 3 horas", likes:1284, comments:84,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 1: como os gregos mediram a Terra, a Lua e o Sol — e o que separa ciência de pseudociência. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Sobre a Ciência",n:"Hewitt, cap. 1 · 13 cards + questão"},
      {k:"Medições científicas",h:"Eratóstenes mede a Terra",p:"Por volta de 235 a.C. comparou a sombra em Alexandria com o Sol a pino em Siena: o ângulo de 7,1° é <mark>1/50 do círculo</mark>, logo a circunferência é 50 × 800 km.",src:"Hewitt, §1.1"},
      {k:"Medições científicas",h:"Aristarco mede a Lua",p:"Num eclipse lunar a sombra da Terra é 2,5 vezes o diâmetro da Lua; corrigindo o afilamento dessa sombra, o diâmetro da Terra é <mark>3,5 vezes</mark> o lunar.",src:"Hewitt, §1.1"},
      {k:"Razão-chave",h:"A razão 1/110",p:"Tanto para a Lua como para o Sol, a razão <mark>diâmetro/distância vale 1/110</mark> — por isso os dois parecem do mesmo tamanho no céu, subentendendo 0,5°.",src:"Hewitt, §1.1"},
      {k:"Imagens de furo",h:"Manchas de luz sob as árvores",p:"As manchas redondas no chão são <mark>imagens do Sol</mark> projetadas pelas frestas entre as folhas; num eclipse parcial elas ficam em forma de crescente.",src:"Hewitt, §1.1"},
      {k:"Matemática",h:"A linguagem da ciência",p:"Expressas em matemática, as ideias científicas ficam <mark>sem ambiguidade</mark> e mais fáceis de comprovar ou negar por experimento.",src:"Hewitt, §1.1"},
      {k:"Método",h:"Não existe um só método",p:"O roteiro usual: identificar o enigma, formular uma <mark>hipótese</mark>, prever consequências, testar e enunciar a lei mais simples — mas muito avanço vem de tentativa e erro.",src:"Hewitt, §1.2"},
      {k:"Atitude científica",h:"Inquirição, integridade, humildade",p:"O sucesso da ciência depende menos de um método do que de uma atitude: estar <mark>disposto a admitir erros</mark>.",src:"Hewitt, §1.2"},
      {k:"Vocabulário",h:"Fato, hipótese, lei, teoria",p:"Fato é a concordância de observadores competentes; hipótese é suposição culta; testada e não negada vira lei; <mark>teoria é a síntese</mark> de um grande corpo de hipóteses.",src:"Hewitt, Termos-chave"},
      {k:"Critério central",h:"Tem de ser refutável",p:"Uma hipótese só é científica se houver um teste capaz de <mark>provar que ela está errada</mark>. Einstein: nenhum experimento prova que estou certo; um só prova que estou errado.",src:"Hewitt, §1.2"},
      {k:"Pseudociência",h:"Falta evidência e teste",p:"A marca da pseudociência é não ter evidência nem teste de falsidade. O rabdomante 'acerta' sempre porque <mark>há água quase em todo lugar</mark> a 100 m de profundidade.",src:"Hewitt, §1.3"},
      {k:"Domínios distintos",h:"Ciência, arte e religião",p:"A ciência descreve a <mark>ordem natural</mark>; a arte, a interpretação e a expressão pessoal; a religião, o propósito e o significado. Domínios diferentes, não rivais.",src:"Hewitt, §1.3"},
      {k:"Ciência × tecnologia",h:"Conhecer e aplicar",p:"A ciência reúne e organiza conhecimento; a tecnologia o aplica. Ela é uma <mark>espada de dois gumes</mark> — quem responde pelo uso são os humanos.",src:"Hewitt, §1.4"},
      {k:"Por que física",h:"A ciência fundamental",p:"Trata de movimento, forças, energia, matéria, calor, som e luz. A <mark>física é subjacente à química</mark>, que por sua vez é subjacente à biologia.",src:"Hewitt, §1.5"},
      {q:true,k:"Questão de revisão",h:"Segundo Hewitt, para uma hipótese ser considerada científica é indispensável que ela:",
        opts:[["A","Seja aceita pela maioria dos cientistas"],["B","Possa ser testada quanto à sua falsidade"],["C","Já tenha sido provada verdadeira em laboratório"],["D","Esteja expressa em linguagem matemática"]],correct:1,
        explain:"O critério é a <b>refutabilidade</b>: tem de existir um teste capaz de mostrar que a hipótese está errada. 'Existe vida inteligente em outros planetas' não é científica porque nenhum resultado poderia negá-la."}
    ]
  },
  {
    user:"fisica.conceitual", av:"I", avc:"#ff375f", disp:"Cap. 2 — Primeira Lei de Newton: Inércia",
    time:"há 5 horas", likes:1476, comments:112,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 2: por que Aristóteles travou a física por 2.000 anos, o que Galileu viu nos planos inclinados e como ΣF = 0 explica tudo que está parado. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Primeira Lei de Newton — Inércia",n:"Hewitt, cap. 2 · 15 cards + questão"},
      {k:"Aristóteles",h:"Natural e violento",p:"Dividia o movimento em natural (pela 'natureza' do objeto, rumo ao seu lugar próprio) e <mark>violento</mark>, imposto de fora por empurrões e puxões.",src:"Hewitt, §2.1"},
      {k:"O erro de 2.000 anos",h:"Cair conforme o peso",p:"Aristóteles afirmava que os corpos caem com rapidez <mark>proporcional ao peso</mark>. A ideia foi aceita como verdade por quase dois milênios por causa de sua autoridade.",src:"Hewitt, §2.1"},
      {k:"Copérnico",h:"A Terra que se move",p:"Propôs que a Terra circunda o Sol, mas <mark>calou-se por anos</mark> temendo perseguição — e também por não conciliar uma Terra móvel com as ideias vigentes de movimento.",src:"Hewitt, §2.1"},
      {k:"Torre de Pisa",h:"Caem juntos",p:"Galileu mostrou que uma pedra duas vezes mais pesada <mark>não cai duas vezes mais rápido</mark>: fora o pequeno efeito do ar, chegam juntas ao chão.",src:"Hewitt, §2.2"},
      {k:"Planos inclinados",h:"A bola busca a mesma altura",p:"Solta numa rampa, a bola sobe a outra até quase a altura inicial. Diminuindo a inclinação ela vai mais longe — num plano horizontal, <mark>iria para sempre</mark>.",src:"Hewitt, §2.2"},
      {k:"Conceito central",h:"Inércia não é força",p:"É a <mark>propriedade da matéria de resistir a mudanças no movimento</mark>. Aristóteles não a reconheceu porque nunca imaginou o movimento sem atrito.",src:"Hewitt, Termos-chave"},
      {k:"Primeira lei",h:"A palavra-chave é permanece",p:"Todo objeto <mark>permanece</mark> em repouso ou em movimento retilíneo uniforme, a menos que uma força resultante não nula seja exercida sobre ele.",src:"Hewitt, §2.3 (Principia)"},
      {k:"Força",h:"Empurrão ou puxão",p:"Pode ser gravitacional, elétrica, magnética ou muscular. Quando há várias, o que importa é a <mark>força resultante</mark> — a soma vetorial de todas elas.",src:"Hewitt, §2.4"},
      {k:"Vetor × escalar",h:"Quando a direção importa",p:"Força, velocidade e aceleração precisam de módulo <mark>e orientação</mark>: são vetoriais. Massa, volume e rapidez se descrevem só pelo módulo: são escalares.",src:"Hewitt, §2.4"},
      {k:"Regra do paralelogramo",h:"A corda mais esticada",p:"Nellie pendurada no varal: as tensões somam-se vetorialmente para anular o peso. O ramo <mark>mais próximo da horizontal</mark> fica com a tensão maior — e é o que rompe.",src:"Hewitt, §2.4"},
      {k:"Equilíbrio",h:"A condição é ΣF = 0",p:"Quando a força resultante é nula, o corpo está em <mark>equilíbrio mecânico</mark>. Num andaime, a soma das tensões para cima iguala a soma dos pesos.",src:"Hewitt, §2.5"},
      {k:"Força de apoio",h:"A mesa empurra de volta",p:"O livro comprime os átomos da mesa, que agem como <mark>minúsculas molas</mark> e empurram para cima. Essa força normal iguala o peso do livro.",src:"Hewitt, §2.6"},
      {k:"Equilíbrio dinâmico",h:"Parado ou uniforme, dá no mesmo",p:"Equilíbrio é <mark>ausência de mudança</mark>, não ausência de movimento: uma bola de boliche rolando em linha reta com rapidez constante também tem ΣF = 0.",src:"Hewitt, §2.7"},
      {k:"Uma força só",h:"Nunca basta para equilibrar",p:"Sob a ação de uma <mark>única força</mark> um objeto jamais está em equilíbrio — a resultante não poderia ser nula. Só com duas ou mais há equilíbrio.",src:"Hewitt, §2.7"},
      {k:"O movimento da Terra",h:"O pássaro e a minhoca",p:"Argumentavam que a 30 km/s a Terra levaria a minhoca embora. Mas árvore, pássaro, minhoca e ar <mark>viajam juntos a 30 km/s</mark> — inércia em ação.",src:"Hewitt, §2.8"},
      {q:true,k:"Questão de revisão",h:"Um avião a jato voa em linha reta horizontal com rapidez constante. Comparando o empuxo dos motores com a força de resistência do ar:",
        opts:[["A","O empuxo é maior, por isso ele avança"],["B","As duas têm o mesmo módulo"],["C","A resistência do ar é maior"],["D","Depende da altitude do voo"]],correct:1,
        explain:"Rapidez constante em linha reta é <b>equilíbrio dinâmico</b>: ΣF = 0. Logo empuxo e resistência do ar se cancelam e têm o mesmo módulo — o avião não ganha nem perde rapidez."}
    ]
  },
  {
    user:"fisica.conceitual", av:"v", avc:"#30d158", disp:"Cap. 3 — Movimento Retilíneo",
    time:"há 8 horas", likes:1193, comments:97,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 3: rapidez, velocidade e aceleração sem confundir — e por que uma pedra cai só 5 m no primeiro segundo. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Movimento Retilíneo",n:"Hewitt, cap. 3 · 16 cards + questão"},
      {k:"Ponto de partida",h:"O movimento é relativo",p:"Todo movimento é descrito <mark>em relação a alguma outra coisa</mark>. Sentada lendo isto, você faz 107.000 km/h em relação ao Sol — e 0 em relação à cadeira.",src:"Hewitt, §3.1"},
      {k:"Rapidez",h:"Distância por unidade de tempo",p:"Galileu foi o primeiro a medir o movimento com <mark>distância e tempo decorrido</mark>, no lugar dos vagos 'lento' e 'rápido'. Sem cronômetro, usava a própria pulsação.",src:"Hewitt, §3.2"},
      {k:"Rapidez",h:"Instantânea × média",p:"A instantânea é a do velocímetro, a de <mark>cada instante</mark>; a média é a distância total dividida pelo tempo total — e as duas quase sempre diferem.",src:"Hewitt, §3.2"},
      {k:"Velocidade",h:"Rapidez com orientação",p:"60 km/h é rapidez; 60 km/h <mark>para o norte</mark> é velocidade. Rapidez é escalar (só módulo), velocidade é vetorial (módulo e orientação).",src:"Hewitt, §3.3"},
      {k:"Velocidade",h:"Quando é constante",p:"Velocidade constante exige rapidez constante <mark>e trajetória retilínea</mark>. Um vagão em curva com rapidez fixa não tem velocidade constante — está acelerando.",src:"Hewitt, §3.3"},
      {k:"Aceleração",h:"A ideia-chave é variação",p:"Aceleração é a <mark>taxa de variação da velocidade</mark> com o tempo. Ganhar 5 km/h a cada segundo é acelerar 5 km/h·s — o segundo aparece duas vezes na unidade.",src:"Hewitt, §3.4"},
      {k:"Aceleração",h:"Fazer curva também acelera",p:"Como engloba mudança de orientação, há aceleração <mark>mesmo com rapidez constante</mark> numa curva. Um carro tem três controles que aceleram: acelerador, freio e volante.",src:"Hewitt, §3.4"},
      {k:"Cuidado",h:"Uma taxa de uma taxa",p:"Hewitt chama a aceleração do <mark>conceito mais difícil do livro</mark>: ela não é a velocidade nem uma variação de velocidade, mas a taxa com que a velocidade varia.",src:"Hewitt, §3.5"},
      {k:"Planos inclinados",h:"Rampa mais íngreme, mais aceleração",p:"Galileu usou rampas para <mark>desacelerar a queda</mark> e poder medi-la. Quanto maior a inclinação, maior a aceleração; na vertical, ela iguala a da queda livre.",src:"Hewitt, §3.4"},
      {k:"Queda livre",h:"O valor de g",p:"Caindo só sob a gravidade, o objeto ganha <mark>10 m/s a cada segundo</mark> (valor médio real: 9,8 m/s²). Hewitt arredonda para 10 porque múltiplos de 10 são mais óbvios.",src:"Hewitt, §3.5"},
      {k:"Quão rápido",h:"v = gt",p:"A velocidade de quem parte do repouso é <mark>g multiplicado pelo tempo</mark>. Depois de 5 s de queda, 50 m/s; depois de 6,5 s, 65 m/s.",src:"Hewitt, §3.5"},
      {k:"Subida e descida",h:"No topo a rapidez é zero",p:"Lançado para cima, o objeto perde 10 m/s por segundo, para no topo e volta como se tivesse sido solto dali. A <mark>aceleração é 10 m/s² o tempo todo</mark>.",src:"Hewitt, §3.5"},
      {k:"Quanto cai",h:"d = ½gt²",p:"A distância é proporcional ao <mark>quadrado do tempo</mark>: 5 m no primeiro segundo, 20 m em 2 s, 45 m em 3 s, 125 m em 5 s.",src:"Hewitt, §3.5"},
      {k:"A pegadinha",h:"5 metros, não 10",p:"No primeiro segundo a pedra cai 5 m mesmo terminando a 10 m/s, porque a <mark>rapidez média foi 5 m/s</mark> — ela começou do zero.",src:"Hewitt, §3.5"},
      {k:"Resistência do ar",h:"Pena e moeda no vácuo",p:"No ar, pena e moeda caem muito diferente; num tubo com o <mark>ar bombeado para fora</mark>, caem com a mesma aceleração.",src:"Hewitt, §3.5"},
      {k:"Vetores velocidade",h:"O avião e o vento transversal",p:"Avião a 80 km/h ao norte com vento de 60 km/h de través: a diagonal do paralelogramo dá <mark>100 km/h</mark>, a 37° a leste do norte.",src:"Hewitt, §3.6"},
      {q:true,k:"Questão de revisão",h:"Uma pedra é solta do repouso. Ao final do primeiro segundo de queda livre (g ≈ 10 m/s²), ela terá caído aproximadamente:",
        opts:[["A","10 m, porque v = gt dá 10 m/s"],["B","5 m"],["C","20 m"],["D","2,5 m"]],correct:1,
        explain:"A rapidez vai de 0 a 10 m/s, então a <b>rapidez média no intervalo é 5 m/s</b> — e 5 m/s × 1 s = 5 m. Confundir 'quão rápido' (v = gt) com 'quanto cai' (d = ½gt²) é o erro mais comum do capítulo."}
    ]
  },
  {
    user:"fisica.conceitual", av:"F", avc:"#ff9f0a", disp:"Cap. 4 — Segunda Lei de Newton",
    time:"há 12 horas", likes:1622, comments:134,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 4: a = F/m, a diferença entre massa e peso, e por que o paraquedista mais pesado chega primeiro ao chão. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Segunda Lei de Newton",n:"Hewitt, cap. 4 · 16 cards + questão"},
      {k:"Ponto de partida",h:"Força produz aceleração",p:"A aceleração é <mark>diretamente proporcional à força resultante</mark>: dobre a resultante e a aceleração dobra; triplique e ela triplica.",src:"Hewitt, §4.1"},
      {k:"Atrito",h:"Átomos que se agarram",p:"Nasce das <mark>irregularidades microscópicas</mark> das superfícies, que se agarram nos pontos de contato. Seu sentido é sempre oposto ao do movimento.",src:"Hewitt, §4.2"},
      {k:"Atrito",h:"Estático vence o de escorregamento",p:"Custa mais força pôr o caixote em movimento do que mantê-lo deslizando. É por isso que o <mark>freio ABS</mark> mantém o pneu na iminência de derrapar, sem travar.",src:"Hewitt, §4.2"},
      {k:"Contraintuitivo",h:"Nem rapidez, nem área",p:"O atrito de escorregamento <mark>não depende da rapidez nem da área de contato</mark>. Pneus extralargos não agarram mais — só distribuem o peso e reduzem aquecimento e desgaste.",src:"Hewitt, §4.2"},
      {k:"Atrito em fluidos",h:"Aí a velocidade importa",p:"Em líquidos e gases o atrito <mark>cresce com a velocidade</mark>. A resistência do ar (força de arraste) é a forma mais comum — dá para sentir na bicicleta.",src:"Hewitt, §4.2"},
      {k:"Massa",h:"A medida da inércia",p:"É a <mark>quantidade de matéria</mark> e também a lentidão com que o objeto responde a qualquer esforço para movê-lo, pará-lo ou desviá-lo.",src:"Hewitt, Termos-chave"},
      {k:"Peso",h:"Força, não matéria",p:"É a <mark>força sobre o objeto devido à gravidade</mark>, igual a mg, com g ≈ 10 N/kg. Um tijolo de 1 kg pesa cerca de 10 N na Terra.",src:"Hewitt, §4.3"},
      {k:"A distinção",h:"Na Lua pesa 1/6",p:"Na Lua o tijolo de 1 kg pesa ~1,6 N, mas sua <mark>massa é a mesma em qualquer lugar</mark>. Sustentar um caminhão é mais fácil lá; acelerá-lo na horizontal, não.",src:"Hewitt, §4.3"},
      {k:"Massa não é volume",h:"Bateria ou caixa vazia?",p:"Do mesmo tamanho, a bateria de carro é muito mais difícil de mover que a caixa de papelão vazia. Massa <mark>não é peso nem volume</mark>.",src:"Hewitt, §4.3"},
      {k:"Inércia resiste",h:"Mais massa, menos aceleração",p:"Para a mesma força, a aceleração é <mark>inversamente proporcional à massa</mark>: dobre a massa e a aceleração cai à metade.",src:"Hewitt, §4.3"},
      {k:"Segunda lei",h:"a = F/m",p:"A aceleração é diretamente proporcional à força resultante, tem o <mark>mesmo sentido dela</mark>, e é inversamente proporcional à massa do objeto.",src:"Hewitt, §4.4"},
      {k:"O enigma resolvido",h:"Por que caem juntos",p:"O tijolo duplo sofre o dobro da atração — mas tem o dobro de inércia. A <mark>razão peso/massa vale g</mark> para todos, como C/D vale π para todo círculo.",src:"Hewitt, §4.5"},
      {k:"Atenção ao erro",h:"Não é força igual",p:"Moeda e pena aceleram igual no vácuo <mark>não porque as forças sejam iguais</mark>, mas porque a razão peso/massa é a mesma. No vácuo falta ar, não gravidade.",src:"Hewitt, §4.5"},
      {k:"Queda não livre",h:"A resultante encolhe",p:"Com ar, a força resultante é o <mark>peso menos a resistência do ar</mark>. Como R cresce com a rapidez, a aceleração vai diminuindo durante a queda.",src:"Hewitt, §4.6"},
      {k:"Velocidade terminal",h:"Quando R iguala mg",p:"Aí a resultante é nula e a aceleração cessa: o corpo cai com <mark>rapidez constante</mark>. Numa pena, poucos cm/s; num paraquedista de barriga, cerca de 200 km/h.",src:"Hewitt, §4.6"},
      {k:"Paraquedas iguais",h:"O mais pesado chega antes",p:"Com paraquedas do mesmo tamanho, o mais pesado precisa <mark>cair mais rápido</mark> para que a resistência iguale seu peso maior — logo tem velocidade terminal maior.",src:"Hewitt, §4.6"},
      {q:true,k:"Questão de revisão",h:"No vácuo, uma moeda e uma pena caem lado a lado com a mesma aceleração. Isso acontece porque:",
        opts:[["A","As forças gravitacionais sobre as duas são iguais"],["B","A razão entre peso e massa é a mesma para as duas"],["C","No vácuo não existe gravidade"],["D","Sem ar, a pena deixa de ter inércia"]],correct:1,
        explain:"Hewitt é enfático: <b>não</b> é porque as forças são iguais — o peso da moeda é bem maior. Elas aceleram igual porque a razão peso/massa vale g para ambas: a força maior é compensada por uma inércia igualmente maior."}
    ]
  },
  {
    user:"fisica.conceitual", av:"⇄", avc:"#5e5ce6", disp:"Cap. 5 — Terceira Lei de Newton",
    time:"há 1 dia", likes:1388, comments:121,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 5: você não pode tocar sem ser tocado. Pares ação-reação, por que eles não se cancelam e como um foguete anda sem ar para empurrar. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Terceira Lei de Newton",n:"Hewitt, cap. 5 · 15 cards + questão"},
      {k:"Ponto de partida",h:"Força é interação",p:"Nenhum empurrão ocorre sozinho. Você <mark>não consegue empurrar uma parede</mark> a menos que ela o empurre de volta — seus dedos curvados são a prova.",src:"Hewitt, §5.1"},
      {k:"Terceira lei",h:"Sempre aos pares",p:"Quando um objeto exerce força sobre outro, este exerce sobre o primeiro uma força <mark>de mesmo módulo e sentido oposto</mark>. Nenhuma das duas existe sem a outra.",src:"Hewitt, §5.2"},
      {k:"Consequência",h:"O boxeador e o lenço",p:"O punho só exerce sobre o lenço de papel <mark>a força que o lenço consegue exercer de volta</mark> — por isso não há como golpeá-lo com força.",src:"Hewitt, §5.1"},
      {k:"Nomenclatura",h:"Ação e reação são rótulos",p:"Newton concluiu que <mark>nenhuma das forças é privilegiada</mark>: tanto faz qual chamamos de ação. O que importa é que são partes de uma única interação.",src:"Hewitt, §5.2"},
      {k:"Locomoção",h:"A reação é que nos move",p:"Você empurra o piso e ele o empurra; o nadador empurra a água e ela o empurra. Sem atrito — no gelo — <mark>não há como gerar a ação</mark>, e ficamos parados.",src:"Hewitt, §5.2"},
      {k:"Cuidado",h:"Ninguém 'tem' força",p:"Força <mark>não é uma propriedade do objeto</mark> como a massa: é parte de uma interação. Um míssil acelerando tem momentum e energia, não força.",src:"Hewitt, §5.2"},
      {k:"A dúvida clássica",h:"Por que não se cancelam",p:"Porque atuam em <mark>objetos diferentes</mark>. A maçã empurra a laranja e a laranja empurra a maçã — mas só uma dessas forças age sobre a laranja, que acelera.",src:"Hewitt, §5.2"},
      {k:"Definindo o sistema",h:"Internas somam zero",p:"Os trilhões de forças interatômicas de uma bola de futebol são pares internos e <mark>se cancelam</mark>. Só uma força externa — o chute — acelera a bola.",src:"Hewitt, §5.2"},
      {k:"Pegadinha",h:"Dois chutes não são um par",p:"Duas forças opostas aplicadas <mark>ao mesmo objeto</mark> não formam par ação-reação, ainda que se cancelem. Ação e reação atuam sempre em objetos diferentes.",src:"Hewitt, §5.2"},
      {k:"Massas diferentes",h:"Canhão e bala",p:"A força na bala iguala a força no canhão, mas <mark>a = F/m</mark>: a mesma força sobre massa pequena dá aceleração grande, e sobre massa grande, pequena.",src:"Hewitt, §5.3"},
      {k:"Vale para a Terra",h:"A rua sobe até você",p:"O objeto em queda puxa a Terra para cima com a mesma força com que é puxado. A aceleração da Terra é <mark>real, mas indetectável</mark> — sua massa é astronômica.",src:"Hewitt, §5.3"},
      {k:"Falsa concepção",h:"O foguete não empurra o ar",p:"Ele recua das 'balas moleculares' que ejeta, como o canhão. Por isso <mark>funciona melhor acima da atmosfera</mark>, onde não há resistência do ar.",src:"Hewitt, §5.3"},
      {k:"Sustentação",h:"Empurrar ar para baixo",p:"Hélice, asa e pássaro forçam o ar para baixo (ação) e o ar os força para cima (reação). Quando a <mark>sustentação iguala o peso</mark>, a aeronave plana.",src:"Hewitt, §5.3"},
      {k:"Decomposição",h:"Todo vetor tem componentes",p:"Qualquer vetor pode ser substituído por <mark>dois componentes perpendiculares</mark> — um horizontal e outro vertical — cuja soma vetorial é ele mesmo.",src:"Hewitt, §5.4"},
      {k:"Plano inclinado",h:"A ladeira reduz a normal",p:"Só o componente de mg perpendicular à superfície a pressiona, então <mark>N encolhe conforme a ladeira</mark>. O componente paralelo é que produz a aceleração.",src:"Hewitt, §5.4"},
      {q:true,k:"Questão de revisão",h:"Um ônibus em alta velocidade colide frontalmente com um besouro. Sobre as forças de impacto e as desacelerações resultantes:",
        opts:[["A","A força sobre o besouro é maior, e sua desaceleração também"],["B","As forças têm o mesmo módulo, mas a desaceleração do besouro é muito maior"],["C","Forças e desacelerações são iguais para os dois"],["D","A força sobre o ônibus é maior porque ele tem mais massa"]],correct:1,
        explain:"Ação e reação formam um par: as <b>forças têm exatamente o mesmo módulo</b>. As acelerações é que diferem, porque a = F/m — a massa minúscula do besouro produz uma desaceleração enorme, enquanto a do ônibus é imperceptível."}
    ]
  },
  {
    user:"fisica.conceitual", av:"p", avc:"#bf5af2", disp:"Cap. 6 — Momentum",
    time:"há 1 dia", likes:1547, comments:129,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 6: inércia em movimento. Por que dobrar os joelhos ao cair salva seus ossos, por que o caratê faz o oposto, e a lei que vale em toda colisão. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Momentum",n:"Hewitt, cap. 6 · 16 cards + questão"},
      {k:"Definição",h:"Inércia em movimento",p:"Momentum é <mark>massa × velocidade</mark> (mv). Um caminhão é mais difícil de parar que um carro na mesma rapidez porque tem mais massa — logo, mais momentum.",src:"Hewitt, §6.1"},
      {k:"Duas vias",h:"Massa grande ou rápida",p:"Um navio lentíssimo pode ter momentum enorme, e uma bala também — <mark>basta um dos fatores ser grande</mark>. Em repouso, qualquer massa tem momentum nulo, porque v = 0.",src:"Hewitt, §6.1"},
      {k:"Impulso",h:"Força vezes tempo",p:"Impulso é <mark>Ft</mark>. Para mudar o momentum importam as duas coisas: a força e quanto tempo ela age. A mesma força por mais tempo muda mais o momentum.",src:"Hewitt, §6.2"},
      {k:"Cuidado",h:"Ninguém 'tem' impulso",p:"Como a força, o impulso <mark>não é posse do objeto</mark> — é o que ele fornece ou sofre numa interação. Momentum, sim, o objeto tem.",src:"Hewitt, §6.2"},
      {k:"A relação central",h:"Ft = Δ(mv)",p:"O impulso é <mark>igual à variação do momentum</mark>. Tanto faz ler como causa ou efeito: os dois estão sempre vinculados.",src:"Hewitt, §6.3"},
      {k:"Caso 1 · Aumentar",h:"O follow-through",p:"Para ganhar momentum, força máxima pelo <mark>maior tempo possível</mark> — é o que faz o golfista ao prolongar o movimento do taco depois do contato.",src:"Hewitt, §6.3"},
      {k:"Caso 2 · Tempo longo",h:"Feno em vez de concreto",p:"Parar exige o mesmo impulso nos dois casos, mas <mark>alongar o tempo reduz a força</mark>. Cem vezes mais tempo, um centésimo da força — a física do airbag.",src:"Hewitt, §6.3"},
      {k:"Caso 2 · No corpo",h:"Dobre os joelhos",p:"Aterrissar com as pernas retas dói: flexionando, você estica o tempo de 10 a 20 vezes e <mark>reduz a força nos ossos na mesma proporção</mark>.",src:"Hewitt, §6.3"},
      {k:"Caso 3 · Tempo curto",h:"O golpe de caratê",p:"Cassy quebra tijolos porque leva um grande momentum e o reduz num <mark>tempo curtíssimo</mark> — o que torna a força de impacto enorme.",src:"Hewitt, §6.3"},
      {k:"Sem contradição",h:"Boxeador × lutador de caratê",p:"O boxeador recua com o golpe para <mark>maximizar o tempo</mark> e sentir menos força; o caratê minimiza o tempo para entregar mais força. Objetivos opostos, mesma equação.",src:"Hewitt, §6.3"},
      {k:"Ricocheteio",h:"Pior que só parar",p:"Parar algo e ainda <mark>arremessá-lo de volta</mark> exige impulso maior do que apenas pará-lo. É por isso que um vaso que ricocheteia na sua cabeça dói mais.",src:"Hewitt, §6.4"},
      {k:"Aplicação",h:"A roda de Pelton",p:"Na Corrida do Ouro, Lester Pelton curvou as pás para que a água <mark>ricocheteasse em U</mark> — o que multiplicou o impulso entregue à roda.",src:"Hewitt, §6.4"},
      {k:"Conservação",h:"Só o externo conta",p:"Forças internas vêm em pares que se cancelam. <mark>Sem impulso externo, o momentum do sistema não muda</mark> — empurrar o painel não move o carro.",src:"Hewitt, §6.5"},
      {k:"Conservação",h:"Canhão e bala somam zero",p:"Antes do disparo o momentum do sistema é nulo; depois <mark>continua nulo</mark>, porque o momentum do canhão é oposto ao da bala. Momentum é vetorial e se cancela.",src:"Hewitt, §6.5"},
      {k:"Tipos de colisão",h:"Elástica × inelástica",p:"Na elástica os corpos ricocheteiam <mark>sem deformação nem calor</mark>; na inelástica há deformação ou calor, e na perfeitamente inelástica eles se grudam.",src:"Hewitt, §6.6"},
      {k:"Conta clássica",h:"Vagões que se acoplam",p:"Um vagão a 10 m/s acopla-se a outro igual em repouso: m × 10 = 2m × V, logo <mark>V = 5 m/s</mark>. Dobrou a massa, caiu à metade a velocidade.",src:"Hewitt, §6.6"},
      {q:true,k:"Questão de revisão",h:"Num carro fora de controle, é melhor colidir com um monte de feno do que com um muro de concreto porque:",
        opts:[["A","O impulso necessário para parar é menor no feno"],["B","O impulso é o mesmo, mas o tempo maior reduz a força"],["C","O feno absorve o momentum do carro"],["D","No feno o momentum final é maior"]],correct:1,
        explain:"O <b>impulso necessário é idêntico</b> nos dois casos — é o mesmo momentum a ser levado a zero. Mas impulso é o produto Ft: alongando t no feno, F cai na mesma proporção. Cem vezes mais tempo significa um centésimo da força."}
    ]
  },
  {
    user:"fisica.conceitual", av:"E", avc:"#64d2ff", disp:"Cap. 7 — Energia",
    time:"há 2 dias", likes:1811, comments:156,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 7: trabalho, potência, EP e EC. Por que dobrar a velocidade quadruplica a distância de frenagem — e por que nenhuma máquina cria energia. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Energia",n:"Hewitt, cap. 7 · 17 cards + questão"},
      {k:"Trabalho",h:"Força vezes distância",p:"Se impulso é força × tempo, trabalho é <mark>força × distância</mark>: W = Fd. Dobre o peso ou dobre a altura e o trabalho dobra.",src:"Hewitt, §7.1"},
      {k:"Pegadinha",h:"Segurar não é trabalhar",p:"A halterofilista que <mark>sustenta</mark> o haltere parado acima da cabeça não realiza trabalho sobre ele: sem deslocamento, não há trabalho — por mais que ela se canse.",src:"Hewitt, §7.1"},
      {k:"Unidade",h:"O joule",p:"1 joule é o trabalho de uma força de 1 N ao longo de 1 m — mais ou menos <mark>erguer uma maçã até a cabeça</mark>. Parar um caminhão a 100 km/h custa megajoules.",src:"Hewitt, §7.1"},
      {k:"Potência",h:"Trabalho por tempo",p:"Subir a escada correndo ou andando dá o mesmo trabalho, mas potências diferentes. <mark>1 watt = 1 joule por segundo</mark>. Seu coração gasta pouco mais de 1 W.",src:"Hewitt, §7.1"},
      {k:"Energia potencial",h:"Guardada na posição",p:"O arco vergado, a mola comprimida, o elástico do estilingue: todos guardam <mark>energia pronta para realizar trabalho</mark>, por causa da posição de suas partes.",src:"Hewitt, §7.2"},
      {k:"EP gravitacional",h:"EP = mgh",p:"Vale <mark>peso × altura</mark> e depende só de mg e h — nunca do caminho. Erguer a bola na vertical, pela rampa ou por degraus dá os mesmos 30 J.",src:"Hewitt, §7.2"},
      {k:"Energia química",h:"Posição em nível micro",p:"Combustíveis, pilhas e alimentos guardam EP na <mark>posição das cargas elétricas</mark> dentro e entre as moléculas — liberada nas reações químicas.",src:"Hewitt, §7.2"},
      {k:"Energia cinética",h:"EC = ½mv²",p:"Energia de movimento. A velocidade entra <mark>ao quadrado</mark>: dobre a rapidez e a energia cinética quadruplica.",src:"Hewitt, §7.3"},
      {k:"História",h:"Du Chatelet e a argila",p:"O debate era mv ou mv². Uma esfera caindo com o dobro da velocidade deixou uma depressão <mark>4 vezes mais funda</mark>, não 2 — e Émilie du Chatelet encerrou a controvérsia.",src:"Hewitt, abertura do cap. 7"},
      {k:"Teorema",h:"Trabalho = ΔEC",p:"O trabalho da <mark>força resultante</mark> é igual à variação da energia cinética. Se o atrito cancela seu empurrão, não há trabalho resultante nem mudança de EC.",src:"Hewitt, §7.4"},
      {k:"Consequência prática",h:"Derrapar quatro vezes mais",p:"O atrito máximo com a estrada é quase o mesmo em qualquer rapidez. Com o <mark>dobro da velocidade</mark>, a EC é 4× maior — e a derrapagem, 4× mais longa.",src:"Hewitt, §7.4"},
      {k:"Lei central",h:"Conservação da energia",p:"A energia <mark>não pode ser criada nem destruída</mark>: só se transforma de uma forma em outra, com a quantidade total sempre constante.",src:"Hewitt, §7.5"},
      {k:"Exemplo",h:"O mergulhador de circo",p:"No topo do mastro, 10.000 J de EP e zero de EC. Na metade da queda, 5.000 e 5.000. Ao chegar embaixo, 0 e 10.000 — a <mark>soma nunca muda</mark>.",src:"Hewitt, §7.5"},
      {k:"Origem",h:"Quase tudo vem do Sol",p:"Chuva, vento, carvão, petróleo e alimento nasceram da luz solar. Escapam dessa regra a energia <mark>nuclear e a das marés</mark> — esta vem da rotação da Terra.",src:"Hewitt, §7.8"},
      {k:"Máquinas",h:"Multiplicam força, não energia",p:"Toda máquina obedece à conservação: <mark>(Fd) na entrada = (Fd) na saída</mark>. Quem multiplica força paga em distância, e vice-versa.",src:"Hewitt, §7.6"},
      {k:"Alavanca",h:"O fulcro perto da carga",p:"Com o fulcro junto à carga, uma força pequena por uma distância grande vira <mark>força grande por distância pequena</mark>. Arquimedes: 'dê-me um ponto de apoio'.",src:"Hewitt, §7.6"},
      {k:"Rendimento",h:"O cemitério é o calor",p:"Nenhuma máquina é 100% eficiente: parte da energia sempre degrada em <mark>energia térmica</mark>. Uma usina a combustível fóssil descarta cerca de dois terços como calor inútil.",src:"Hewitt, §7.7"},
      {q:true,k:"Questão de revisão",h:"Um carro a 100 km/h derrapa com as rodas travadas até parar. Comparada à de um carro idêntico a 50 km/h, sua distância de derrapagem será:",
        opts:[["A","Duas vezes maior"],["B","Quatro vezes maior"],["C","A mesma, pois o atrito é igual"],["D","Oito vezes maior"]],correct:1,
        explain:"A energia cinética depende do <b>quadrado</b> da rapidez: o dobro da velocidade dá quatro vezes mais EC. Como o atrito máximo com a estrada é praticamente o mesmo nas duas situações, é preciso quatro vezes mais distância para dissipar toda essa energia."}
    ]
  },
  {
    user:"fisica.conceitual", av:"↻", avc:"#0a84ff", disp:"Cap. 8 — Movimento de Rotação",
    time:"há 2 dias", likes:1704, comments:148,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 8: rapidez tangencial e angular, torque, centro de gravidade e a força centrífuga que não existe. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Movimento de Rotação",n:"Hewitt, cap. 8 · 20 cards + questão"},
      {k:"Duas rapidezes",h:"Tangencial × angular",p:"Num carrossel rígido, <mark>todos giram com a mesma rapidez angular</mark> (mesmas RPM) — mas quem está na borda tem rapidez tangencial maior, porque percorre mais caminho.",src:"Hewitt, §8.1"},
      {k:"Relação",h:"v ~ rω",p:"A rapidez tangencial é proporcional <mark>à distância ao eixo e à rapidez angular</mark>. Duas vezes mais longe do centro, duas vezes mais rápido.",src:"Hewitt, §8.1"},
      {k:"Aplicação",h:"Por que o trem não descarrila",p:"Não é o friso: as rodas são levemente <mark>cônicas</mark>. Na curva, a roda externa rola pela parte larga e a interna pela estreita — e o par se autocentraliza.",src:"Hewitt, §8.1"},
      {k:"Inércia rotacional",h:"Onde está a massa importa",p:"Resistência a mudar o estado de rotação. Diferente da inércia comum, depende da <mark>distribuição da massa em torno do eixo</mark> — massa longe do eixo, mais inércia.",src:"Hewitt, §8.2"},
      {k:"Aplicação",h:"O bastão do equilibrista",p:"Massa longe do eixo dá ao bastão muita inércia rotacional: ele <mark>resiste a girar</mark> e dá ao equilibrista o tempo de se reequilibrar. Quanto mais comprido, melhor.",src:"Hewitt, §8.2"},
      {k:"Contraintuitivo",h:"O cilindro vence o aro",p:"Descendo a mesma rampa, <mark>qualquer cilindro sólido chega antes de qualquer aro</mark> — não importam massas nem diâmetros. O aro tem mais 'letargia por massa'.",src:"Hewitt, §8.2"},
      {k:"Torque",h:"A contraparte da força",p:"Força muda o movimento; torque muda o estado de rotação. <mark>Torque = braço de alavanca × força</mark>.",src:"Hewitt, §8.3"},
      {k:"Torque",h:"A gangorra desigual",p:"Crianças de pesos diferentes se equilibram porque o que conta é o torque: <mark>500 N × 1,5 m = 250 N × 3 m</mark>. Torque resultante nulo, nenhuma rotação.",src:"Hewitt, §8.3"},
      {k:"Detalhe fino",h:"Braço é a perpendicular",p:"O braço de alavanca é a <mark>distância perpendicular</mark> entre o eixo e a linha de ação da força. Por isso a chave de boca rende mais puxada em ângulo reto.",src:"Hewitt, §8.3"},
      {k:"Equilíbrio",h:"Duas condições, não uma",p:"Além de ΣF = 0, o equilíbrio mecânico exige <mark>torque resultante nulo</mark> (Στ = 0). Quem está em equilíbrio não acelera nem linearmente nem em rotação.",src:"Hewitt, §8.3"},
      {k:"Centro de massa",h:"A posição média da massa",p:"Num corpo simétrico coincide com o centro geométrico. Quando o peso entra na conta, chamamos de <mark>centro de gravidade</mark> — na prática, o mesmo ponto.",src:"Hewitt, §8.4"},
      {k:"Propriedade notável",h:"O CM segue a parábola",p:"O bastão atirado cambaleia, mas seu centro de massa descreve uma <mark>parábola suave</mark>. Uma bala que explode: o CG dos fragmentos segue a trajetória original.",src:"Hewitt, §8.4"},
      {k:"Curiosidade",h:"Pode não haver massa lá",p:"O CG de uma rosca está <mark>no centro do furo</mark>; o de um bumerangue, fora do material. E o da atmosfera terrestre fica no centro da Terra.",src:"Hewitt, §8.4"},
      {k:"Tombamento",h:"Quando o CG sai da base",p:"O objeto tomba quando seu centro de gravidade <mark>ultrapassa a base de apoio</mark> — daí o torque desequilibrado o vira. Base larga e CG baixo dão estabilidade.",src:"Hewitt, §8.4"},
      {k:"Força centrípeta",h:"F = mv²/r",p:"Qualquer força <mark>orientada para o centro</mark>. Não é uma força básica da natureza: é o nome do papel que a tensão, a gravidade ou o atrito desempenham.",src:"Hewitt, §8.5"},
      {k:"A grande confusão",h:"Centrífuga é fictícia",p:"Se o barbante rompe, a lata não sai radialmente: segue <mark>tangente</mark> à curva. Nada a empurra para fora — o que existe é inércia.",src:"Hewitt, §8.6"},
      {k:"Sistema girante",h:"Uma força sem contraparte",p:"Dentro do sistema que gira, a centrífuga parece tão real quanto a gravidade — mas <mark>não tem par ação-reação</mark>. Não há nada lá fora puxando.",src:"Hewitt, §8.6"},
      {k:"Aplicação",h:"Gravidade simulada",p:"Um hábitat espacial que gira pressiona os ocupantes contra a parede interna. Para 1 g a <mark>1 RPM</mark>, a estrutura precisaria de uns 2 km de diâmetro.",src:"Hewitt, §8.6"},
      {k:"Momentum angular",h:"Inércia rotacional × ω",p:"A 'inércia em rotação'. Para um corpo pequeno frente ao raio, vale <mark>mvr</mark>. Só um torque externo resultante é capaz de alterá-lo.",src:"Hewitt, §8.7"},
      {k:"Conservação",h:"A patinadora que acelera",p:"Sem torque externo, I × ω é constante: recolhendo os braços ela <mark>reduz I e a rapidez angular dispara</mark>. Pelo mesmo princípio, a Lua se afasta 1/4 cm por rotação da Terra.",src:"Hewitt, §8.8"},
      {q:true,k:"Questão de revisão",h:"Você gira uma lata presa a um barbante numa trajetória circular horizontal e o barbante rompe. Desprezando a gravidade, a lata:",
        opts:[["A","Voa radialmente para fora, afastando-se do centro"],["B","Segue em linha reta, tangente à trajetória circular"],["C","Mantém a trajetória circular por inércia"],["D","Para imediatamente onde o barbante rompeu"]],correct:1,
        explain:"Não existe força centrífuga real empurrando a lata para fora. Sem o puxão do barbante não sobra força alguma, então vale a primeira lei de Newton: a lata segue <b>tangente</b> à curva, pela inércia."}
    ]
  },
  {
    user:"fisica.conceitual", av:"g", avc:"#ff375f", disp:"Cap. 9 — Gravidade",
    time:"há 3 dias", likes:1935, comments:171,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 9: a lei que vale da maçã à galáxia. Como se pesou a Terra, por que há duas marés por dia e por que o Sol quase não as faz. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Gravidade",n:"Hewitt, cap. 9 · 20 cards + questão"},
      {k:"Síntese newtoniana",h:"Uma lei só para tudo",p:"A grande sacada foi perceber que a força que puxa a maçã é <mark>a mesma que mantém a Lua</mark> — rompendo com a ideia de leis separadas para a Terra e para os céus.",src:"Hewitt, §9.1"},
      {k:"A lei",h:"Massas e distância",p:"Todo corpo atrai qualquer outro com força <mark>proporcional ao produto das massas</mark> e inversamente proporcional ao quadrado da distância entre seus centros.",src:"Hewitt, §9.1"},
      {k:"Insight-chave",h:"A Lua cai em volta",p:"A Lua <mark>cai</mark> — sai da reta que seguiria sem gravidade. Sua velocidade tangencial é que a faz cair em volta da Terra, em vez de sobre ela.",src:"Hewitt, §9.1"},
      {k:"Rigor científico",h:"Vinte anos na gaveta",p:"Os primeiros cálculos de Newton <mark>não fecharam</mark>, e ele guardou os papéis por duas décadas — fatos prevalecem sobre hipóteses bonitas. Só publicou após corrigir os dados.",src:"Hewitt, §9.1"},
      {k:"A constante G",h:"Gravidade é fraquíssima",p:"G = 6,67 × 10⁻¹¹ N·m²/kg². Valor minúsculo: a gravidade é a <mark>mais fraca das quatro forças fundamentais</mark>. Só a sentimos por causa da enormidade da Terra.",src:"Hewitt, §9.2"},
      {k:"Experimento",h:"Pesando o planeta",p:"Cavendish mediu G com uma balança de torção em 1798. Com G na mão, a própria equação entrega a <mark>massa da Terra: 6 × 10²⁴ kg</mark>.",src:"Hewitt, §9.2"},
      {k:"Inverso do quadrado",h:"A pistola de tinta",p:"A tinta que cobre 1 mm de espessura a 1 m se espalha por <mark>quatro vezes a área</mark> a 2 m — logo 1/4 da espessura. Vale para gravidade, luz, som e radiação.",src:"Hewitt, §9.3"},
      {k:"Cuidado",h:"A distância é entre centros",p:"Uma árvore duas vezes mais alta <mark>não reduz o peso da maçã a 1/4</mark>: ela teria de ter a altura do raio da Terra. Para perder 1% do peso, suba 32 km.",src:"Hewitt, §9.3"},
      {k:"Peso",h:"A força sobre o apoio",p:"Definição ampla: peso é a <mark>força que você exerce sobre o piso que o sustenta</mark>. Num elevador acelerando, ele muda — ainda que mg não mude.",src:"Hewitt, §9.4"},
      {k:"A confusão clássica",h:"Sem peso, com gravidade",p:"O astronauta em órbita é imponderável não por falta de gravidade, mas por <mark>falta de força de sustentação</mark>: ele está em queda livre contínua.",src:"Hewitt, §9.4"},
      {k:"Marés",h:"Diferença, não intensidade",p:"As marés vêm da <mark>diferença</mark> entre a atração lunar nos lados próximo e distante da Terra — como uma bola de gelatina puxada mais de um lado, que se alonga.",src:"Hewitt, §9.5"},
      {k:"Marés",h:"Dois bulbos, duas marés",p:"O alongamento cria bulbos <mark>em lados opostos</mark>. A Terra gira sob eles, então cada ponto passa por dois — daí duas marés altas por dia, a cada 24 h e 50 min.",src:"Hewitt, §9.5"},
      {k:"Contraintuitivo",h:"O Sol atrai 180× mais",p:"E ainda assim faz menos da metade da maré lunar: tão longe, ele atrai <mark>quase igualmente os dois lados</mark> da Terra, e a diferença fica pequena.",src:"Hewitt, §9.5"},
      {k:"Tipos de maré",h:"Sizígia e quadratura",p:"Alinhados Sol-Terra-Lua (lua nova ou cheia), os efeitos somam: <mark>marés de sizígia</mark>, as mais extremas. Em quadratura (meia-lua), eles se cancelam em parte.",src:"Hewitt, §9.5"},
      {k:"Escala importa",h:"Nem lago, nem corpo",p:"Sem partes significativamente mais próximas da Lua, não há maré. Um <mark>melão de 1 kg acima da sua cabeça</mark> produz ~200 vezes mais efeito de maré em você que a Lua.",src:"Hewitt, §9.5"},
      {k:"Campos",h:"Linhas de campo",p:"O espaço em torno de uma massa fica alterado: é o <mark>campo gravitacional</mark>. Onde as linhas se adensam, o campo é mais intenso — e ele obedece ao inverso do quadrado.",src:"Hewitt, §9.6"},
      {k:"Física imaginativa",h:"Zero no centro",p:"Caindo por um túnel, sua aceleração diminui porque há <mark>cada vez menos massa abaixo</mark>. No centro da Terra o campo é nulo: rapidez máxima, aceleração zero.",src:"Hewitt, §9.6"},
      {k:"Limite",h:"Gravidade não se blinda",p:"Ao contrário da força elétrica, que atrai e repele, a gravidade <mark>só atrai</mark> — então não há blindagem. Os eclipses previstos com precisão comprovam isso.",src:"Hewitt, §9.6"},
      {k:"Buracos negros",h:"Quando a escape passa de c",p:"Se o Sol encolhesse para menos de 3 km de raio sem perder massa, a <mark>velocidade de escape excederia a da luz</mark>. Nada escaparia — nem a luz.",src:"Hewitt, §9.7"},
      {k:"Triunfo da lei",h:"Netuno na ponta do lápis",p:"Desvios na órbita de Urano levaram Adams e Leverrier a <mark>calcular onde estaria um oitavo planeta</mark>. Berlim apontou o telescópio e achou Netuno na mesma noite.",src:"Hewitt, §9.8"},
      {q:true,k:"Questão de revisão",h:"O Sol atrai os oceanos da Terra com força cerca de 180 vezes maior que a Lua, mas produz marés menos da metade das lunares. A razão é que:",
        opts:[["A","A atração solar é mais fraca por causa da distância"],["B","O que gera maré é a diferença de atração entre os lados opostos da Terra, e a do Sol é pequena"],["C","O Sol só provoca marés na atmosfera"],["D","A Lua se move mais rápido no céu"]],correct:1,
        explain:"Maré não vem da <b>intensidade</b> da atração, mas da <b>diferença</b> entre as atrações nos lados próximo e distante da Terra. O Sol está tão longe que atrai os dois lados quase igualmente; a Lua, perto, atrai bem mais o lado voltado para ela."}
    ]
  },
  {
    user:"fisica.conceitual", av:"⌒", avc:"#30d158", disp:"Cap. 10 — Projéteis e Satélites",
    time:"há 3 dias", likes:1768, comments:159,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 10: por que um satélite é só um projétil que cai rápido demais para acertar a Terra — e por que a altitude não tem nada a ver com fugir da gravidade. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Projéteis e Satélites",n:"Hewitt, cap. 10 · 19 cards + questão"},
      {k:"Chave do capítulo",h:"Componentes independentes",p:"Todo o mistério dos projéteis se dissolve ao separar a velocidade: o <mark>horizontal e o vertical não se afetam</mark>. Juntos produzem a curva.",src:"Hewitt, §10.1"},
      {k:"Os dois movimentos",h:"Constante e acelerado",p:"Na horizontal não há força, então a velocidade é <mark>constante</mark>, como uma bola de boliche. Na vertical vale a queda livre, com g.",src:"Hewitt, §10.1"},
      {k:"Forma da trajetória",h:"É uma parábola",p:"Aceleração só na vertical e velocidade constante na horizontal produzem uma <mark>parábola</mark> — desde que a resistência do ar seja desprezível.",src:"Hewitt, §10.1"},
      {k:"Experimento clássico",h:"As duas balas chegam juntas",p:"Uma bala disparada horizontalmente e outra simplesmente solta da mesma altura <mark>caem a mesma distância vertical</mark> — e tocam o chão no mesmo instante.",src:"Hewitt, §10.1"},
      {k:"Regra prática",h:"5t² abaixo da reta",p:"Depois de t segundos, o projétil está <mark>5t² metros abaixo</mark> de onde estaria sem gravidade. Impressionante: essa distância não depende do ângulo de lançamento.",src:"Hewitt, §10.1"},
      {k:"No topo",h:"Sobra só o horizontal",p:"No zênite o componente vertical é nulo, então a rapidez ali é <mark>igual ao componente horizontal</mark> — e é a menor de toda a trajetória.",src:"Hewitt, §10.1"},
      {k:"Alcance",h:"Ângulos que somam 90°",p:"Lançados com a mesma rapidez, <mark>30° e 60° dão o mesmo alcance</mark>. O máximo fica em 45° — desprezando o ar.",src:"Hewitt, §10.1"},
      {k:"Na vida real",h:"Bem menos que 45°",p:"Com resistência do ar, a bola de beisebol vai mais longe saindo entre <mark>25° e 34°</mark>. Para dardo e peso, o ângulo ótimo também cai — mas por outro motivo: o lançamento é mais lento na vertical.",src:"Hewitt, §10.1"},
      {k:"Dado geométrico",h:"5 metros por 8 km",p:"A superfície da Terra <mark>desce 5 m a cada 8 km</mark> de tangente. Esse único número é a chave de todo o movimento de satélites.",src:"Hewitt, §10.2"},
      {k:"A grande ideia",h:"Cair em volta, não sobre",p:"Como qualquer projétil cai 5 m no primeiro segundo, quem percorrer <mark>8 km nesse mesmo segundo</mark> acompanha a curvatura e nunca chega ao chão. São 8 km/s — 29.000 km/h.",src:"Hewitt, §10.2"},
      {k:"Falsa concepção",h:"A altitude é pelo ar",p:"Satélites ficam acima de 150 km para <mark>fugir da resistência do ar, não da gravidade</mark>. A 200 km, a gravidade é quase igual à da superfície.",src:"Hewitt, §10.2"},
      {k:"Montanha de Newton",h:"Do tiro curto à órbita",p:"Newton imaginou balas disparadas cada vez mais rápido do alto de uma montanha: a trajetória fica <mark>menos curva até fechar num círculo</mark>. Estaria em órbita.",src:"Hewitt, §10.2"},
      {k:"Órbita circular",h:"A gravidade não acelera",p:"Movendo-se sempre <mark>perpendicular à força</mark>, o satélite não ganha nem perde rapidez: a gravidade muda só a direção. Queda livre a rapidez constante.",src:"Hewitt, §10.3"},
      {k:"Períodos",h:"Mais alto, mais lento",p:"Em órbita baixa o período é cerca de <mark>90 minutos</mark>. A 5,5 raios terrestres de altitude são 24 h — o satélite fica parado sobre o mesmo ponto. A Lua leva 27,3 dias.",src:"Hewitt, §10.3"},
      {k:"Órbita elíptica",h:"Passar de 8 km/s",p:"Um pouco mais rápido e o satélite ultrapassa o círculo: sobe contra a gravidade <mark>perdendo rapidez</mark>, e recupera tudo ao cair de volta. Círculo é uma elipse de focos coincidentes.",src:"Hewitt, §10.4"},
      {k:"Kepler",h:"As três leis",p:"1) A órbita é uma elipse com o Sol num foco. 2) O raio varre <mark>áreas iguais em tempos iguais</mark>. 3) T² é proporcional a r³ para todos os planetas.",src:"Hewitt, §10.5"},
      {k:"Limite de Kepler",h:"Faltava-lhe a inércia",p:"Kepler achou as leis mas <mark>não viu que um satélite é só um projétil</mark>: como Aristóteles, supunha a força na direção do movimento. Newton uniu Kepler e Galileu.",src:"Hewitt, §10.5"},
      {k:"Energia",h:"EC + EP é constante",p:"Na elipse, a EP é máxima no apogeu e a EC é máxima no perigeu — mas a <mark>soma das duas é a mesma em toda a órbita</mark>.",src:"Hewitt, §10.6"},
      {k:"Rapidez de escape",h:"11,2 km/s da Terra",p:"Equivale a <mark>62 MJ por quilograma</mark>. Acima disso o projétil vai desacelerando para sempre, mas nunca para. Para escapar do Sol daqui, seriam 42,5 km/s.",src:"Hewitt, §10.7"},
      {q:true,k:"Questão de revisão",h:"Satélites e ônibus espaciais são colocados em órbita a altitudes de 150 km ou mais. O motivo principal dessa altitude é:",
        opts:[["A","Escapar da atração gravitacional da Terra"],["B","Ficar acima da atmosfera, praticamente livre da resistência do ar"],["C","Reduzir o peso da carga lançada"],["D","Poder atingir a velocidade de escape"]],correct:1,
        explain:"A 200 km de altura a gravidade é <b>quase tão intensa quanto na superfície</b> — e é justamente ela que curva a trajetória e mantém o satélite em órbita. A altitude serve para fugir do arraste do ar; sem gravidade, o satélite sairia em linha reta."}
    ]
  },
  {
    user:"fisica.conceitual", av:"⚛", avc:"#ff9f0a", disp:"Cap. 11 — A Natureza Atômica da Matéria",
    time:"há 4 dias", likes:1652, comments:143,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 11: a frase que Feynman salvaria de um cataclismo. Quão pequenos e quantos são os átomos, e por que você respira átomos que já foram de outra pessoa. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"A Natureza Atômica da Matéria",n:"Hewitt, cap. 11 · 20 cards + questão"},
      {k:"Origem da ideia",h:"Gregos contra Aristóteles",p:"No século V a.C. já se falava de um pedaço mínimo indivisível. Mas Aristóteles defendeu os <mark>quatro elementos</mark> — e sua visão durou mais de 2.000 anos.",src:"Hewitt, §11.1"},
      {k:"Retomada",h:"Dalton explica a química",p:"No início dos anos 1800, John Dalton explicou com sucesso as reações químicas <mark>supondo que a matéria fosse feita de átomos</mark> — mas sem evidência direta.",src:"Hewitt, §11.1"},
      {k:"A evidência",h:"Movimento browniano",p:"Em 1827 Brown viu grãos de pólen saltando sem parar na água. É o resultado visível das <mark>colisões com moléculas invisíveis</mark> — como um balão movido por uma torcida.",src:"Hewitt, §11.1"},
      {k:"Fecho histórico",h:"Einstein, 1905",p:"A explicação de Einstein do movimento browniano permitiu <mark>obter as massas atômicas</mark>. Só então a realidade dos átomos deixou de ser contestada.",src:"Hewitt, §11.1"},
      {k:"A frase de Feynman",h:"O que ele salvaria",p:"Se tudo fosse destruído e só uma frase pudesse passar: 'todas as coisas são feitas de átomos — <mark>partículas em movimento perpétuo</mark>, que se atraem a certa distância e se repelem quando comprimidas'.",src:"Hewitt, abertura do cap. 11"},
      {k:"Escala",h:"Átomo, maçã, Terra",p:"O diâmetro do átomo está para o da maçã como <mark>o da maçã está para o da Terra</mark>. Estamos, em tamanho, a meio caminho entre os átomos e as estrelas.",src:"Hewitt, §11.2"},
      {k:"Quantidade",h:"10²³ num dedal",p:"Um grama de água tem cerca de <mark>10²³ átomos</mark> — mais átomos num dedal de água do que gotas de água em todos os rios e lagos do mundo.",src:"Hewitt, §11.2"},
      {k:"Movimento",h:"Respiramos uns aos outros",p:"As moléculas do ar se espalham tão rápido que, em poucos anos, <mark>qualquer pessoa no mundo inalará algum átomo que você exalou</mark> hoje.",src:"Hewitt, §11.2"},
      {k:"Permanência",h:"Os átomos não têm idade",p:"Os do corpo de um bebê são tão velhos quanto os de um idoso: quase todos nasceram em <mark>estrelas que explodiram</mark> antes do Sistema Solar. Somos apenas zeladores deles.",src:"Hewitt, §11.2"},
      {k:"Por que não vemos",h:"A questão é a onda",p:"A difração impede ver detalhes <mark>menores que o comprimento de onda</mark> usado. A luz visível é grande demais para revelar um átomo — como ondas do mar diante da corrente da âncora.",src:"Hewitt, §11.3"},
      {k:"Como se vê então",h:"Elétrons em vez de luz",p:"A primeira imagem de átomos individuais (1970) usou um <mark>feixe de elétrons</mark>, cujo comprimento de onda é muito menor. Depois vieram os microscópios de tunelamento.",src:"Hewitt, §11.3"},
      {k:"Método",h:"Modelo não é retrato",p:"O átomo planetário é uma <mark>abstração que ajuda a prever</mark>, não uma fotografia. Os elétrons não orbitam como planetas — mas o modelo abriu caminho para os seguintes.",src:"Hewitt, §11.3"},
      {k:"O núcleo",h:"Densidade absurda",p:"Quase toda a massa cabe em poucos quatrilionésimos do volume. Núcleos nus empacotados numa <mark>ervilha pesariam 133 milhões de toneladas</mark>.",src:"Hewitt, §11.4"},
      {k:"Núcleons",h:"Próton e nêutron",p:"São o mesmo tipo de partícula em estados diferentes: <mark>neutro é nêutron, positivo é próton</mark>. Ambos formados por quarks, e todos os prótons são cópias perfeitas entre si.",src:"Hewitt, §11.4"},
      {k:"Vocabulário",h:"Elemento × átomo",p:"Elemento é a <mark>substância feita de um só tipo de átomo</mark>; átomo é a partícula individual. Mais de 99% da Terra vem de apenas uma dúzia de elementos.",src:"Hewitt, §11.4"},
      {k:"Tabela periódica",h:"Como um calendário",p:"Da esquerda para a direita, cada elemento ganha um próton; de cima para baixo, ganha <mark>uma camada de elétrons</mark>. À direita ficam os gases nobres, de camada externa completa.",src:"Hewitt, §11.5"},
      {k:"Tamanho atômico",h:"Quem manda é a força elétrica",p:"Mais carga no núcleo <mark>puxa os elétrons para mais perto</mark> e encolhe as camadas. Por isso o urânio, com 92 elétrons, não é muito maior que o hidrogênio.",src:"Hewitt, §11.5"},
      {k:"Isótopos",h:"Mesmo elemento, outra massa",p:"Mesmo número de prótons, <mark>número diferente de nêutrons</mark>. O número de massa é inteiro e identifica o isótopo; a massa atômica é a média ponderada e tem casas decimais.",src:"Hewitt, §11.6"},
      {k:"Composto × mistura",h:"Sódio + cloro = sal",p:"No composto surge algo novo: o sódio reage violentamente com água, o cloro é venenoso, e juntos dão um <mark>cristal inofensivo</mark>. Na mistura, nada se combina quimicamente.",src:"Hewitt, §11.7"},
      {k:"Antimatéria",h:"Aniquilação total",p:"Núcleo negativo e pósitrons no lugar dos elétrons. Ao encontrar a matéria, <mark>converte 100% da massa em energia</mark> — fissão e fusão convertem menos de 1%.",src:"Hewitt, §11.9"},
      {q:true,k:"Questão de revisão",h:"O átomo de urânio tem 92 elétrons, contra apenas 1 do hidrogênio. Comparando os diâmetros dos dois átomos:",
        opts:[["A","O urânio é cerca de 92 vezes maior"],["B","O urânio não é significativamente maior que o hidrogênio"],["C","O urânio é bem menor, por ter mais nêutrons"],["D","Os dois têm exatamente o mesmo diâmetro"]],correct:1,
        explain:"Quanto maior a carga do núcleo, <b>mais perto ele puxa os elétrons</b>, e as camadas encolhem. O acréscimo de elétrons é compensado por esse encolhimento — quem fixa o tamanho do átomo é a força elétrica."}
    ]
  },
  {
    user:"fisica.conceitual", av:"◼", avc:"#5e5ce6", disp:"Cap. 12 — Sólidos",
    time:"há 4 dias", likes:1421, comments:118,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 12: cristais, densidade, lei de Hooke e arcos. E por que uma formiga do tamanho de um elefante não conseguiria sair do chão. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Sólidos",n:"Hewitt, cap. 12 · 19 cards + questão"},
      {k:"Cristais",h:"Redes de átomos",p:"Metais, sais e minerais são cristais: <mark>arranjos ordenados e tridimensionais</mark> de átomos, como tabuleiros de xadrez em 3D. Confirmado com raios X em 1912.",src:"Hewitt, §12.1"},
      {k:"A técnica",h:"Difração de raios X",p:"Von Laue viu raios X se separarem em padrões ao atravessar um cristal; os Bragg criaram a fórmula que converte o padrão em <mark>distâncias entre átomos</mark>.",src:"Hewitt, §12.1"},
      {k:"Aplicação famosa",h:"A dupla hélice",p:"Os padrões de difração de raios X do DNA obtidos por <mark>Wilkins e Rosalind Franklin</mark> em 1953 forneceram os dados que levaram Watson e Crick à dupla hélice.",src:"Hewitt, §12.1"},
      {k:"Amorfos",h:"Sólidos sem ordem",p:"Borracha, vidro e plástico <mark>não têm arranjo repetitivo</mark>. Suas partículas conservam alguma liberdade — daí a elasticidade da borracha e o vidro que escoa sob tensão prolongada.",src:"Hewitt, §12.1"},
      {k:"Massa específica",h:"Massa por volume",p:"'O ferro é mais pesado que a madeira?' é pergunta ambígua; a correta é sobre densidade. Ela é <mark>propriedade do material</mark>, independe da quantidade.",src:"Hewitt, §12.2"},
      {k:"Curiosidade",h:"O irídio ganha por espaçamento",p:"Seus átomos têm massa <mark>menor</mark> que os de platina, ouro e urânio — mas ficam tão próximos que cabem mais num cm³. Resultado: 22.650 kg/m³, o mais denso da Terra.",src:"Hewitt, §12.2"},
      {k:"Caso do gelo",h:"Por que flutua",p:"Ao congelar, a água se expande: a mesma massa passa a ocupar <mark>mais volume</mark>. Densidade menor que a da água líquida — e o gelo flutua.",src:"Hewitt, §12.2"},
      {k:"Elasticidade",h:"Voltar à forma original",p:"Mola, bola de beisebol e arco são elásticos: <mark>retornam à forma</mark> quando a força deformante cessa. Argila e chumbo são inelásticos.",src:"Hewitt, §12.3"},
      {k:"Lei de Hooke",h:"F proporcional a Δx",p:"A deformação é <mark>diretamente proporcional à força</mark>: dobre o peso na mola e ela distende o dobro. Descoberta por Robert Hooke no século XVII.",src:"Hewitt, §12.3"},
      {k:"Limite",h:"Onde Hooke deixa de valer",p:"Passando do <mark>limite elástico</mark>, o material não volta mais ao estado original — fica permanentemente deformado, e a proporcionalidade se perde.",src:"Hewitt, §12.3"},
      {k:"Dois esforços",h:"Tensão e compressão",p:"Puxar é tensão, esmagar é compressão. Ao curvar uma régua, a face externa fica <mark>sob tensão</mark> e a interna sob compressão.",src:"Hewitt, §12.4"},
      {k:"Conceito-chave",h:"A camada neutra",p:"Entre a face tensionada e a comprimida existe uma região <mark>sem esforço algum</mark>. Furar o galho de uma árvore ali é o que menos o enfraquece.",src:"Hewitt, §12.4"},
      {k:"Engenharia",h:"A viga em I",p:"O esforço se concentra nas bordas, então o aço do meio é quase dispensável. A alma só <mark>mantém as bordas unidas</mark> — mesma resistência, peso muito menor.",src:"Hewitt, §12.4"},
      {k:"Arcos",h:"A compressão reforça",p:"Rocha rompe fácil sob tensão, mas resiste à compressão. No arco, a carga <mark>aperta as pedras umas contra as outras</mark> — e com a forma certa, nem cimento é preciso.",src:"Hewitt, §12.5"},
      {k:"Duas curvas",h:"Parábola ou catenária",p:"Para carga horizontal uniforme, como uma ponte, a forma ideal é a <mark>parábola</mark>. Para sustentar só o próprio peso, é a catenária — a curva de uma corrente pendurada.",src:"Hewitt, §12.5"},
      {k:"Cúpulas",h:"Arco girado 360°",p:"Gira-se o arco em torno de um eixo vertical e a carga vira compressão outra vez — por isso a cúpula <mark>vence grandes vãos sem colunas</mark> no meio. O iglu já fazia isso.",src:"Hewitt, §12.5"},
      {k:"Demonstração",h:"O pintinho e a casca",p:"É mais fácil romper o ovo de dentro para fora porque aí basta vencer a <mark>tensão, que é fraca</mark>. De fora, seria preciso vencer a compressão da casca.",src:"Hewitt, §12.5"},
      {k:"Mudanças de escala",h:"Quadrado contra cubo",p:"Dobrando as dimensões, a área da seção cresce <mark>4 vezes e o volume 8 vezes</mark>. A resistência vem da área; o peso, do volume.",src:"Hewitt, §12.6"},
      {k:"Consequência",h:"Pernas finas, pernas grossas",p:"Por isso pernilongos e antílopes têm pernas finas e elefantes as têm grossas — e por isso <mark>King Kong não sairia do chão</mark>. As baleias escapam da regra pelo empuxo da água.",src:"Hewitt, §12.6"},
      {q:true,k:"Questão de revisão",h:"Um atleta é ampliado ao dobro da altura e da largura, mantendo as proporções. Sua capacidade de erguer o próprio peso:",
        opts:[["A","Dobra, pois ele ficou duas vezes maior"],["B","Cai à metade"],["C","Permanece a mesma"],["D","Quadruplica"]],correct:1,
        explain:"A força depende da <b>área</b> da seção transversal, que quadruplica; o peso depende do <b>volume</b>, que fica oito vezes maior. Quatro vezes mais forte carregando oito vezes mais peso dá metade da capacidade relativa."}
    ]
  },
  {
    user:"fisica.conceitual", av:"≈", avc:"#64d2ff", disp:"Cap. 13 — Líquidos",
    time:"há 5 dias", likes:1583, comments:137,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 13: pressão, empuxo e Arquimedes. Por que um navio de ferro flutua, por que as montanhas são mais fundas que altas e o erro mais comum sobre empuxo. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Líquidos",n:"Hewitt, cap. 13 · 20 cards + questão"},
      {k:"Pressão",h:"Força dividida pela área",p:"Dois blocos idênticos têm o mesmo peso, mas o que está <mark>de pé exerce mais pressão</mark> — a mesma força espalhada por menos área. Unidade: pascal (Pa).",src:"Hewitt, §13.1"},
      {k:"Demonstração",h:"A cama de pregos",p:"Dá para deitar sem se ferir porque o peso se distribui por <mark>centenas de pontas</mark>: a força total é a mesma, mas a pressão em cada ponta fica pequena.",src:"Hewitt, §13.1"},
      {k:"Pressão em líquido",h:"Peso específico × profundidade",p:"Só duas coisas importam: a <mark>densidade do líquido e a profundidade</mark>. Duas vezes mais fundo, duas vezes mais pressão.",src:"Hewitt, §13.2"},
      {k:"Contraintuitivo",h:"O volume não conta",p:"A pressão média sobre uma represa depende da <mark>profundidade média, não do volume</mark> represado. Um lago extenso e raso pressiona menos que um açude pequeno e fundo.",src:"Hewitt, §13.2"},
      {k:"Consequência",h:"A água busca seu nível",p:"A pressão no fundo só depende da altura, então recipientes ligados <mark>igualam seus níveis</mark>. Os romanos não confiavam nisso e ergueram aquedutos desnecessariamente elaborados.",src:"Hewitt, §13.2"},
      {k:"Direções",h:"Pressão em todos os lados",p:"A pressão atua igualmente em todas as direções — para os lados e para cima também. Já a <mark>força resultante é perpendicular</mark> à superfície.",src:"Hewitt, §13.2"},
      {k:"Empuxo",h:"Peso que parece desaparecer",p:"A pedra submersa é fácil de erguer e fica pesada ao sair da água. A <mark>força de empuxo</mark> aponta para cima, contra a gravidade.",src:"Hewitt, §13.3"},
      {k:"A causa",h:"Diferença de pressão",p:"As componentes horizontais se cancelam, mas o fundo do objeto está <mark>mais fundo que o topo</mark> — e portanto sob pressão maior. Sobra uma resultante para cima.",src:"Hewitt, §13.3"},
      {k:"Volume deslocado",h:"Igual ao do objeto",p:"Um objeto totalmente submerso desloca <mark>exatamente seu próprio volume</mark> de líquido — o que dá um jeito prático de medir volumes de forma irregular.",src:"Hewitt, §13.3"},
      {k:"Arquimedes",h:"O princípio",p:"Um corpo imerso sofre empuxo para cima <mark>igual ao peso do fluido que desloca</mark>. Vale para líquidos e gases, e para corpos parcial ou totalmente submersos.",src:"Hewitt, §13.4"},
      {k:"O erro mais comum",h:"Quem manda é o volume",p:"O empuxo depende do <mark>volume</mark> submerso, nunca do peso do objeto. Um litro de chumbo submerso recebe o empuxo de um litro de água: 10 N.",src:"Hewitt, §13.5"},
      {k:"Afundar ou flutuar",h:"Aí sim entra o peso",p:"Compara-se empuxo e peso, o que equivale a comparar densidades: <mark>mais denso que o fluido afunda</mark>, menos denso flutua, igual fica onde está.",src:"Hewitt, §13.5"},
      {k:"Na natureza",h:"Três estratégias",p:"O peixe ajusta o <mark>volume</mark> com a bolsa de ar; o submarino ajusta o peso com tanques de lastro; e o crocodilo engole pedras para nadar mais submerso.",src:"Hewitt, §13.5"},
      {k:"Flutuação",h:"Desloca o próprio peso",p:"Um objeto flutuante desloca um peso de fluido <mark>igual ao seu próprio peso</mark>. Um navio de 10.000 toneladas precisa ser grande o bastante para deslocar 10.000 toneladas de água.",src:"Hewitt, §13.6"},
      {k:"Navio de ferro",h:"A forma resolve",p:"O bloco maciço desloca só 1/8 do seu peso e afunda. Moldado em <mark>tigela</mark>, o mesmo ferro desloca muito mais água — e para de afundar quando o empuxo iguala seu peso.",src:"Hewitt, §13.6"},
      {k:"Geologia",h:"Montanhas flutuantes",p:"O gelo tem 0,9 da densidade da água, então 90% do iceberg fica submerso. A crosta tem 0,85 da densidade do manto: as montanhas são <mark>mais fundas que altas</mark>.",src:"Hewitt, §13.6"},
      {k:"Pascal",h:"A pressão se transmite inteira",p:"Uma variação de pressão num ponto de um fluido em repouso é transmitida <mark>integralmente a todos os outros pontos</mark>.",src:"Hewitt, §13.7"},
      {k:"Prensa hidráulica",h:"Força, nunca energia",p:"Pistão 50 vezes maior sustenta 50 vezes mais carga — mas <mark>sobe 50 vezes menos</mark>. Como a alavanca, multiplica força à custa da distância.",src:"Hewitt, §13.7"},
      {k:"Tensão superficial",h:"Por que a gota é esférica",p:"A superfície tende a se contrair e buscar a <mark>menor área possível</mark> — e a esfera é a forma de menor área para um dado volume.",src:"Hewitt, §13.8"},
      {k:"A causa",h:"Atração desequilibrada",p:"A molécula do interior é puxada igualmente em todas as direções; a da superfície <mark>não tem ninguém acima</mark> para puxá-la. O saldo aponta para dentro.",src:"Hewitt, §13.8"},
      {q:true,k:"Questão de revisão",h:"Dois blocos sólidos de tamanhos idênticos são submersos em água: um de chumbo e outro de alumínio. A força de empuxo é:",
        opts:[["A","Maior sobre o de chumbo, que é mais pesado"],["B","Igual sobre os dois"],["C","Maior sobre o de alumínio, que é menos denso"],["D","Nula sobre o de chumbo, porque ele afunda"]],correct:1,
        explain:"O empuxo é igual ao peso do <b>volume de fluido deslocado</b> — e blocos de tamanhos iguais deslocam o mesmo volume de água. O peso do objeto submerso decide se ele afunda, não o quanto de empuxo ele recebe."}
    ]
  },
  {
    user:"fisica.conceitual", av:"○", avc:"#ff375f", disp:"Cap. 14 — Gases",
    time:"há 5 dias", likes:1497, comments:126,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 14: vivemos no fundo de um oceano de ar. Por que sucção não existe, por que o canudo tem limite de 10,3 m e como a asa sustenta o avião. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Gases",n:"Hewitt, cap. 14 · 19 cards + questão"},
      {k:"A atmosfera",h:"Um acordo feliz",p:"Ela existe por um equilíbrio entre duas tendências: a <mark>energia cinética</mark> das moléculas, que as espalharia, e a gravidade, que as manteria coladas ao solo.",src:"Hewitt, §14.1"},
      {k:"Espessura",h:"Tudo em 30 km",p:"Metade da atmosfera está abaixo de 5,6 km e <mark>99% abaixo de 30 km</mark> — apenas 0,5% do raio da Terra. Acima, ela se dilui até se confundir com o vazio.",src:"Hewitt, §14.1"},
      {k:"Pressão atmosférica",h:"O ar tem peso",p:"Ao nível do mar, 1 m³ de ar tem massa de 1,25 kg — <mark>o ar de um quarto pesa tanto quanto uma criança</mark>. A pressão atmosférica é o peso desse ar.",src:"Hewitt, §14.2"},
      {k:"Por que não sentimos",h:"Equilíbrio por dentro",p:"A pressão interna do corpo <mark>iguala a do ar em volta</mark>, então não há força resultante. É o mesmo motivo pelo qual não se sente o peso de um saco de água dentro da piscina.",src:"Hewitt, §14.2"},
      {k:"Conceito central",h:"Sucção não existe",p:"Vácuo é <mark>ausência de matéria</mark> — o nada não exerce força. Nos hemisférios de Magdeburg, dois grupos de cavalos falharam porque a atmosfera os empurrava, não os sugava.",src:"Hewitt, §14.2"},
      {k:"O número",h:"Cerca de 100 kPa",p:"A coluna de ar sobre 1 m² ao nível do mar pesa uns 100.000 N, o que dá <mark>101,3 kPa</mark> — uma atmosfera.",src:"Hewitt, §14.2"},
      {k:"Barômetro",h:"Os 76 cm de Torricelli",p:"A coluna de mercúrio para onde o peso da atmosfera <mark>equilibra o peso do líquido</mark> no tubo. A largura do tubo não importa — só a altura.",src:"Hewitt, §14.2"},
      {k:"Com água daria?",h:"Precisaria de 10,3 m",p:"O mercúrio é <mark>13,6 vezes mais denso</mark> que a água, então um barômetro de água teria de ter 13,6 × 0,76 m — alto demais para ser prático.",src:"Hewitt, §14.2"},
      {k:"Consequência",h:"O limite do canudo",p:"Sugar só <mark>reduz a pressão dentro</mark> do canudo; quem levanta o líquido é a atmosfera. Nem o melhor vácuo puxaria água acima de 10,3 m ao nível do mar.",src:"Hewitt, §14.2"},
      {k:"Lei de Boyle",h:"PV = constante",p:"À temperatura fixa, pressão e volume são <mark>inversamente proporcionais</mark>: comprima o gás à metade do volume e a pressão dobra.",src:"Hewitt, §14.3"},
      {k:"Aplicação vital",h:"Nunca prenda a respiração",p:"A 10,3 m de profundidade a pressão é de duas atmosferas. Subir prendendo o ar faria os pulmões tenderem <mark>ao dobro do volume</mark> — a primeira lição do mergulho.",src:"Hewitt, §14.3"},
      {k:"Empuxo do ar",h:"Arquimedes também aqui",p:"Um corpo rodeado por ar recebe empuxo <mark>igual ao peso do ar deslocado</mark>. A pressão que empurra por baixo é maior que a que empurra por cima.",src:"Hewitt, §14.4"},
      {k:"Quanto vale",h:"12 N por metro cúbico",p:"Qualquer objeto de 1 m³ imerso no ar recebe cerca de 12 N de empuxo. Se sua massa passar de <mark>1,2 kg</mark>, ele cai; se for menor, ele sobe.",src:"Hewitt, §14.4"},
      {k:"Balões",h:"Até igualar densidades",p:"O balão sobe enquanto desloca mais peso de ar do que o seu próprio. Ele para quando a <mark>densidade média dele iguala a do ar</mark> ao redor.",src:"Hewitt, §14.4"},
      {k:"Continuidade",h:"Estreitou, acelerou",p:"O fluxo é contínuo, então a mesma quantidade passa por qualquer seção: onde o cano <mark>afina, o fluido acelera</mark>. É o riacho que corre mais rápido no desfiladeiro.",src:"Hewitt, §14.5"},
      {k:"Bernoulli",h:"Mais rápido, menos pressão",p:"Onde a rapidez do fluido cresce, a <mark>pressão interna decresce</mark>. Vale para fluxo suave e laminar, sem turbulência nem atrito relevantes.",src:"Hewitt, §14.5"},
      {k:"No cotidiano",h:"Telhado e capota",p:"O ar acelera ao passar pela cumeeira e a pressão lá cai. A pressão maior <mark>de dentro empurra o telhado para fora</mark> — o mesmo que estufa a capota de lona.",src:"Hewitt, §14.5"},
      {k:"Sustentação",h:"Duas explicações válidas",p:"O <mark>ângulo de ataque</mark> faz o ar correr mais rápido por cima, e a diferença de pressão levanta a asa. Pela terceira lei: a asa joga ar para baixo e o ar empurra a asa para cima.",src:"Hewitt, §14.5"},
      {k:"Efeito",h:"Por que a bola curva",p:"A rotação arrasta uma fina camada de ar e <mark>amontoa as linhas de corrente de um lado só</mark>. A pressão fica maior no lado oposto e a trajetória se curva.",src:"Hewitt, §14.5"},
      {q:true,k:"Questão de revisão",h:"Ao beber refrigerante com um canudo, o que faz o líquido subir até a sua boca é:",
        opts:[["A","A força de sucção criada pelos pulmões"],["B","O peso da atmosfera empurrando a superfície do líquido"],["C","O vácuo puxando o líquido para cima"],["D","A tensão superficial do refrigerante"]],correct:1,
        explain:"Vácuo é <b>ausência de matéria</b> e não pode exercer força alguma. Sugando, você só reduz a pressão dentro do canudo; quem empurra o líquido para cima é o peso da atmosfera sobre a bebida. Daí o limite de 10,3 m ao nível do mar."}
    ]
  },
  {
    user:"fisica.conceitual", av:"T", avc:"#ff9f0a", disp:"Cap. 15 — Temperatura, Calor e Dilatação",
    time:"há 6 dias", likes:1538, comments:131,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 15: a matéria não contém calor. Temperatura × energia interna, o calor específico da água que define climas, e por que o gelo flutua. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Temperatura, Calor e Dilatação",n:"Hewitt, cap. 15 · 20 cards + questão"},
      {k:"Temperatura",h:"Média, não total",p:"É proporcional à <mark>energia cinética translacional média</mark> das moléculas. Rotação e vibração também existem, mas não definem temperatura.",src:"Hewitt, §15.1"},
      {k:"Escalas",h:"Celsius, Fahrenheit, Kelvin",p:"A Kelvin é a dos cientistas porque parte da energia: o zero absoluto, <mark>–273 °C</mark>, é onde não há energia cinética alguma a ceder. Nela não existem números negativos.",src:"Hewitt, §15.1"},
      {k:"Distinção crucial",h:"Dois litros × um litro",p:"Dois litros de água fervendo têm o <mark>dobro da energia cinética molecular</mark> de um litro — mas exatamente a mesma temperatura, porque a média por molécula não mudou.",src:"Hewitt, §15.1"},
      {k:"Micro-ondas",h:"Girar não cozinha",p:"As micro-ondas fazem as moléculas de água <mark>girar</mark>. O que cozinha é a energia de translação que elas passam às moléculas vizinhas ao ricochetear nelas.",src:"Hewitt, §15.1"},
      {k:"Detalhe fino",h:"O termômetro mede a si",p:"Ele indica a <mark>própria temperatura</mark>, depois de trocar energia com o objeto até o equilíbrio térmico. Por isso precisa ser pequeno: medir uma gota mudaria a gota.",src:"Hewitt, §15.1"},
      {k:"Calor",h:"Energia em trânsito",p:"É a energia transferida de um corpo a outro <mark>por causa da diferença de temperatura</mark>. Uma vez transferida, ela deixa de ser calor.",src:"Hewitt, §15.2"},
      {k:"Descoberta",h:"Rumford e os canhões",p:"Perfurando canhões, ele notou que <mark>quanto mais cega a broca, mais calor saía</mark> — e sem fim, enquanto os cavalos girassem. A fonte era o movimento, não um fluido guardado no metal.",src:"Hewitt, abertura do cap. 15"},
      {k:"Consequência",h:"Matéria não contém calor",p:"O que a matéria contém é <mark>energia interna</mark>: a soma de todas as energias dentro dela — translação, rotação, vibração e energia potencial molecular.",src:"Hewitt, §15.2"},
      {k:"Sentido do fluxo",h:"Temperatura, não energia",p:"Uma tigela de água morna tem <mark>mais energia interna</mark> que uma tachinha incandescente — mas o calor flui da tachinha para a água. Sempre do mais quente para o mais frio.",src:"Hewitt, §15.2"},
      {k:"Unidades",h:"caloria e Caloria",p:"1 caloria aquece 1 g de água em 1 °C. A do rótulo dos alimentos é a <mark>Caloria com C maiúsculo</mark> — mil vezes maior. E 1 caloria = 4,184 joules.",src:"Hewitt, §15.2"},
      {k:"Calor específico",h:"Uma inércia térmica",p:"É o calor necessário para elevar em um grau a temperatura de uma unidade de massa. Funciona como <mark>resistência a mudar de temperatura</mark>.",src:"Hewitt, §15.3"},
      {k:"A fórmula",h:"Q = mcΔT",p:"Calor transferido é <mark>massa × calor específico × variação de temperatura</mark>. Um grama de ferro precisa de cerca de um oitavo do calor que a água pede.",src:"Hewitt, §15.3"},
      {k:"Água",h:"Campeã em armazenar",p:"Absorve muito calor com <mark>pouca elevação de temperatura</mark> — e demora a esfriar. É por isso que serve para refrigerar motores.",src:"Hewitt, §15.4"},
      {k:"Efeito global",h:"A Europa agradece",p:"A Corrente do Golfo leva água quente ao Atlântico Norte e <mark>solta essa energia no ar</mark>. Sem o alto calor específico da água, a Europa seria gelada como o nordeste do Canadá.",src:"Hewitt, §15.4"},
      {k:"Efeito local",h:"Costa oeste × costa leste",p:"Na mesma latitude, São Francisco tem invernos mais amenos e verões mais frescos que Washington, porque lá o vento vem <mark>do oceano para a terra</mark>.",src:"Hewitt, §15.4"},
      {k:"Dilatação",h:"Engenharia tem de prever",p:"A Golden Gate encurta mais de um metro nos dias frios. Daí as <mark>juntas de expansão</mark> em pontes e calçadas — e trilhos soldados são assentados no dia mais quente do verão.",src:"Hewitt, §15.5"},
      {k:"Aplicação",h:"A lâmina bimetálica",p:"Dois metais com taxas de dilatação diferentes soldados lado a lado: ao aquecer, a tira <mark>verga para um lado</mark> e abre ou fecha um circuito. É o coração do termostato.",src:"Hewitt, §15.5"},
      {k:"Líquidos",h:"Dilatam mais que sólidos",p:"A gasolina transborda do tanque no calor porque <mark>dilata mais que o metal</mark>. E o mercúrio sobe no termômetro porque dilata mais que o vidro do tubo.",src:"Hewitt, §15.5"},
      {k:"A anomalia",h:"Água entre 0 e 4 °C",p:"Nessa faixa a água <mark>contrai ao aquecer</mark>: os cristais ocos remanescentes vão colapsando, e esse efeito vence a agitação molecular até os 4 °C. Depois, ela dilata como todo mundo.",src:"Hewitt, §15.5"},
      {k:"Por que importa",h:"Lagos congelam por cima",p:"Ao congelar, a água aumenta uns <mark>10% de volume</mark> e fica menos densa. Se fosse mais densa a 0 °C, o gelo afundaria e os lagos congelariam do fundo para cima.",src:"Hewitt, §15.5"},
      {q:true,k:"Questão de revisão",h:"Comparados a um litro de água fervendo, dois litros de água fervendo:",
        opts:[["A","Têm a mesma temperatura e a mesma energia interna"],["B","Têm a mesma temperatura, mas o dobro da energia interna"],["C","Têm o dobro da temperatura"],["D","Têm temperatura maior, pois há mais moléculas agitadas"]],correct:1,
        explain:"Temperatura é a energia cinética translacional <b>média por molécula</b> — idêntica nos dois casos. Energia interna é o <b>total</b>, e com o dobro das moléculas ela dobra. Confundir as duas coisas é o erro central deste capítulo."}
    ]
  },
  {
    user:"fisica.conceitual", av:"≋", avc:"#5e5ce6", disp:"Cap. 16 — Transferência de Calor",
    time:"há 6 dias", likes:1466, comments:124,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 16: condução, convecção e radiação. Por que dá para andar sobre brasas, por que a geada só pega na grama e como funciona o efeito estufa. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Transferência de Calor",n:"Hewitt, cap. 16 · 19 cards + questão"},
      {k:"Panorama",h:"Três caminhos",p:"O calor sempre vai do mais quente para o mais frio, e faz isso de três maneiras: <mark>condução, convecção e radiação</mark>.",src:"Hewitt, cap. 16"},
      {k:"Condução",h:"Elétrons frouxos conduzem",p:"Metais conduzem bem porque seus <mark>elétrons externos são fracamente ligados</mark> e carregam energia por colisões. A prata lidera, seguida do cobre.",src:"Hewitt, §16.1"},
      {k:"Isolantes",h:"Elétrons bem presos",p:"Lã, madeira, cortiça e isopor <mark>seguram firme seus elétrons externos</mark> — e por isso conduzem mal. É o que permite cabo de madeira em panela quente.",src:"Hewitt, §16.1"},
      {k:"Demonstração extrema",h:"Andar sobre brasas",p:"Funciona porque a madeira em brasa tem <mark>condutividade baixíssima</mark>: mesmo a alta temperatura, transfere pouco calor aos pés. Sobre metal quente, queimaria.",src:"Hewitt, §16.1"},
      {k:"O ar isola",h:"Lã, penas, fibra de vidro",p:"O poder isolante desses materiais vem sobretudo dos <mark>espaços de ar</mark> que eles aprisionam. Se o ar conduzisse bem, um dia de 20 °C pareceria congelante.",src:"Hewitt, §16.1"},
      {k:"Correção de linguagem",h:"Frio não entra",p:"Não existe frio penetrando na casa: o que existe é <mark>calor escapando</mark>. Isolar serve para impedir a saída, não a entrada.",src:"Hewitt, §16.1"},
      {k:"Detalhe importante",h:"Isolante só retarda",p:"Nenhum isolamento <mark>impede</mark> a passagem do calor — ele apenas diminui a taxa. Uma sala aquecida e bem isolada ainda vai esfriar, só mais devagar.",src:"Hewitt, §16.1"},
      {k:"Sensação",h:"Azulejo × madeira",p:"À mesma temperatura, o azulejo parece mais frio porque <mark>conduz melhor</mark> e puxa calor do pé mais rápido. Sentir quente ou frio é sobre taxa, não sobre temperatura.",src:"Hewitt, §16.1"},
      {k:"Convecção",h:"O fluido se move",p:"Aquecido por baixo, o fluido fica menos denso e <mark>o empuxo o empurra para cima</mark>; o mais frio desce para ocupar o lugar. Nasce uma corrente circulando.",src:"Hewitt, §16.2"},
      {k:"Efeito surpreendente",h:"Expandir esfria",p:"Ao se expandir, as moléculas colidem mais com moléculas <mark>que se afastam</mark> — e perdem rapidez. Sopre com os lábios contraídos e sinta: o ar sai frio.",src:"Hewitt, §16.2"},
      {k:"Aplicação",h:"A brisa marítima",p:"De dia a terra esquenta mais rápido, o ar sobe e <mark>o ar do mar vem substituí-lo</mark>. De noite inverte, porque a água conserva o calor por mais tempo.",src:"Hewitt, §16.2"},
      {k:"Radiação",h:"Não precisa de meio",p:"A energia do Sol atravessa o vácuo, então não é condução nem convecção: é <mark>onda eletromagnética</mark> — de rádio a raios gama, passando pelo infravermelho e o visível.",src:"Hewitt, §16.3"},
      {k:"Relação-chave",h:"Mais quente, mais alta",p:"A frequência de pico da radiação é <mark>proporcional à temperatura absoluta</mark>. Por isso a estrela azul é mais quente que a branca, e esta mais que a vermelha.",src:"Hewitt, §16.3"},
      {k:"Consequência",h:"A Terra brilha em infravermelho",p:"O Sol, quentíssimo, emite ondas curtas — boa parte visível. A Terra, fria, emite <mark>ondas longas invisíveis</mark>: é a radiação terrestre. Tudo acima do zero absoluto emite algo.",src:"Hewitt, §16.3"},
      {k:"Simetria",h:"Bom emissor, bom absorvedor",p:"As duas qualidades andam juntas — <mark>por isso tudo tende a uma temperatura comum</mark>. Se não fosse assim, um bom absorvedor ficaria eternamente mais quente que a vizinhança.",src:"Hewitt, §16.3"},
      {k:"Por que é escuro",h:"O buraco na caixa",p:"Absorver bem significa <mark>refletir pouco</mark> — e o que reflete pouco parece escuro. A luz que entra numa cavidade ricocheteia e é absorvida, então a abertura parece negra.",src:"Hewitt, §16.3"},
      {k:"Observação do dia a dia",h:"Geada só na grama",p:"Grama e palha isolam do solo e <mark>irradiam mais do que recebem</mark>, ficando abaixo da temperatura do ar. Concreto e pedra recebem calor conduzido do solo e não congelam.",src:"Hewitt, §16.3"},
      {k:"Lei do resfriamento",h:"Taxa proporcional a ΔT",p:"A taxa de resfriamento é <mark>proporcional à diferença de temperatura</mark> com a vizinhança — e vale também para o aquecimento.",src:"Hewitt, §16.4"},
      {k:"Efeito estufa",h:"Válvula de mão única",p:"Ondas curtas do Sol atravessam o vidro ou a atmosfera; o interior aquece e reemite <mark>ondas longas, que não conseguem sair</mark>. Sem ele, a Terra estaria a –18 °C.",src:"Hewitt, §16.5"},
      {q:true,k:"Questão de revisão",h:"Dois recipientes metálicos idênticos, um pintado de preto e um espelhado, são cheios com água quente. Sobre o resfriamento:",
        opts:[["A","O preto esfria mais rápido"],["B","O espelhado esfria mais rápido"],["C","Os dois esfriam no mesmo ritmo"],["D","O preto esquenta em vez de esfriar"]],correct:0,
        explain:"Bons emissores são também bons absorvedores. A superfície preta <b>emite melhor</b> e portanto perde energia mais rápido. Invertendo o teste — os dois com água gelada diante de uma lareira — é o preto que esquenta primeiro."}
    ]
  },
  {
    user:"fisica.conceitual", av:"❄", avc:"#64d2ff", disp:"Cap. 17 — Mudanças de Fase",
    time:"há 1 semana", likes:1611, comments:139,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 17: evaporar resfria, condensar aquece — e ferver também resfria. Água que congela fervendo, regelo e o calor latente. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Mudanças de Fase",n:"Hewitt, cap. 17 · 19 cards + questão"},
      {k:"Panorama",h:"Quatro fases",p:"Acrescente energia ao gelo e ele vira água; mais energia, vapor; mais ainda, as moléculas se rompem em íons e elétrons — a fase de <mark>plasma</mark>.",src:"Hewitt, §17.1"},
      {k:"Evaporação",h:"Só as mais rápidas escapam",p:"As moléculas da superfície que recebem energia suficiente <mark>se libertam do líquido</mark>. É uma seleção: escapam justamente as mais velozes.",src:"Hewitt, §17.2"},
      {k:"Consequência",h:"Evaporar resfria",p:"Quem fica para trás são as <mark>moléculas mais lentas</mark> — logo a energia cinética média cai, e o líquido esfria. Se todas as rapidezes escapassem igual, não haveria resfriamento.",src:"Hewitt, §17.2"},
      {k:"Na natureza",h:"Suor, cantil e cachorro",p:"O suor é o <mark>termostato do corpo</mark>. O cantil com tecido úmido resfria a água por dentro. E o cão, sem glândulas sudoríparas no corpo, arfa; o porco chafurda na lama.",src:"Hewitt, §17.2"},
      {k:"Sublimação",h:"Sólido direto a gás",p:"A água congelada também 'evapora', <mark>sem passar pela fase líquida</mark>. É o que encolhe cubos de gelo esquecidos no congelador e some com a neve em dias secos.",src:"Hewitt, §17.2"},
      {k:"Condensação",h:"O contrário aquece",p:"A molécula de gas que se junta ao líquido entrega seu excesso de energia. Daí o <mark>vapor queimar mais que a água fervente</mark> na mesma temperatura.",src:"Hewitt, §17.3"},
      {k:"Dica prática",h:"Seque-se dentro do boxe",p:"Ali a <mark>condensação compensa a evaporação</mark> e você não sente frio. Saindo da área úmida, a evaporação vence e bate o arrepio.",src:"Hewitt, §17.3"},
      {k:"Clima",h:"Seco × úmido",p:"No Arizona a evaporação vence e você sente frio; em Nova Orleans a <mark>condensação sobre a pele</mark> aquece — mesma temperatura, sensações opostas.",src:"Hewitt, §17.3"},
      {k:"Microfísica",h:"Lenta gruda, rápida ricocheteia",p:"Moléculas velozes de água <mark>ricocheteiam ao colidir</mark>; as lentas se aglomeram. Por isso condensação e saturação são mais prováveis no ar frio.",src:"Hewitt, §17.3"},
      {k:"Nuvens",h:"Neblina é questão de altitude",p:"Ar úmido sobe, expande, esfria — e as moléculas lentas se juntam em torno de poeira e sais. A <mark>neblina é uma nuvem formada junto ao solo</mark>.",src:"Hewitt, §17.3"},
      {k:"Ebulição",h:"Evaporação por dentro",p:"A bolha só sobrevive se a <mark>pressão de vapor lá dentro vencer</mark> a pressão do líquido e da atmosfera em volta. Abaixo do ponto de ebulição, ela é esmagada.",src:"Hewitt, §17.4"},
      {k:"Depende da pressão",h:"Panela e altitude",p:"Mais pressão sobe o ponto de ebulição: é a panela de pressão. Menos pressão o abaixa — em Denver a água ferve a <mark>95 °C</mark> e o ovo de 3 minutos sai cru.",src:"Hewitt, §17.4"},
      {k:"Na natureza",h:"O gêiser",p:"Coluna estreita e profunda: a <mark>pressão no fundo eleva o ponto de ebulição</mark>. A ebulição começa lá embaixo, empurra a água acima, a pressão cai e a erupção explode.",src:"Hewitt, §17.4"},
      {k:"Contraintuitivo",h:"Ferver resfria",p:"Aquecer e ferver são coisas diferentes: a água a 100 °C <mark>não esquenta mais</mark> porque a ebulição retira energia na mesma taxa em que o fogo entrega.",src:"Hewitt, §17.4"},
      {k:"Demonstração",h:"Ferver e congelar juntos",p:"Reduzindo a pressão numa campânula, a água ferve à temperatura ambiente e o <mark>resfriamento a leva até 0 °C</mark> — formando gelo sobre a água que ainda ferve. É assim que se faz café desidratado.",src:"Hewitt, §17.4"},
      {k:"Fusão",h:"Mesma temperatura, dois sentidos",p:"Aquecida, a agitação vence as forças atrativas e o sólido funde. As substâncias <mark>congelam à mesma temperatura em que fundem</mark>.",src:"Hewitt, §17.5"},
      {k:"Impurezas",h:"Sal abaixa o ponto",p:"Íons estranhos <mark>atrapalham a formação dos cristais hexagonais</mark> de gelo, então é preciso ir mais frio para congelar. O gelo que se forma primeiro é quase sempre água pura.",src:"Hewitt, §17.5"},
      {k:"Regelo",h:"Derreter sob pressão",p:"A pressão esmaga os cristais ocos e derrete o gelo; solta a pressão, ele <mark>recongela</mark>. É o que faz a bola de neve grudar — e num frio extremo ela não se forma.",src:"Hewitt, §17.5"},
      {k:"Calor latente",h:"80 e 540 calorias",p:"Fundir 1 g de gelo custa 80 cal <mark>sem alterar a temperatura</mark>; vaporizar 1 g de água custa 540 cal. Esses mesmos valores são devolvidos no caminho inverso.",src:"Hewitt, §17.6"},
      {q:true,k:"Questão de revisão",h:"Água fervendo a 100 °C continua recebendo calor do fogo, mas sua temperatura não sobe. Isso acontece porque:",
        opts:[["A","O termômetro deixa de funcionar a 100 °C"],["B","A ebulição é um processo de resfriamento que compensa o aquecimento"],["C","A água deixa de absorver energia nessa temperatura"],["D","A pressão atmosférica impede o aquecimento"]],correct:1,
        explain:"Aquecer a água e fervê-la são coisas diferentes. A ebulição <b>retira energia</b> junto com as moléculas que escapam, na mesma taxa em que o fogo a entrega. Sem esse resfriamento a temperatura subiria sem parar — e é justamente bloqueando a ebulição que a panela de pressão passa dos 100 °C."}
    ]
  },
  {
    user:"fisica.conceitual", av:"Δ", avc:"#bf5af2", disp:"Cap. 18 — Termodinâmica",
    time:"há 1 semana", likes:1729, comments:152,
    cap:"Hewitt, Física Conceitual (12ª ed.), cap. 18: as duas leis que mataram o moto-perpétuo. Zero absoluto, processos adiabáticos, Carnot e por que nenhuma máquina converte tudo. Deslize 👉",
    slides:[
      {cover:true,tag:"Carrossel de estudo",h2:"Termodinâmica",n:"Hewitt, cap. 18 · 19 cards + questão"},
      {k:"Fundamentos",h:"Dois pilares",p:"A termodinâmica se apoia na <mark>conservação da energia</mark> e no fato de que o calor flui espontaneamente do quente para o frio — nunca ao contrário.",src:"Hewitt, §18.1"},
      {k:"Zero absoluto",h:"Existe um limite para o frio",p:"Todo gás varia <mark>1/273 do seu volume a 0 °C</mark> por grau Celsius. Resfriado 273 °C, o volume iria a zero — o que revela a temperatura mínima possível.",src:"Hewitt, §18.2"},
      {k:"Escala Kelvin",h:"Sem números negativos",p:"O zero absoluto é 0 K, ou <mark>–273,15 °C</mark>. As divisões têm o mesmo tamanho das da escala Celsius, então um kelvin e um grau Celsius são iguais.",src:"Hewitt, §18.2"},
      {k:"Energia interna",h:"Tudo somado",p:"Energia cinética molecular, potencial entre moléculas, química, nuclear e até a <mark>energia de existir</mark> (E = mc²). Em termodinâmica, o que interessa são as variações.",src:"Hewitt, §18.3"},
      {k:"Primeira lei",h:"Duas saídas para o calor",p:"Calor adicionado ao sistema = <mark>aumento da energia interna + trabalho externo</mark> realizado por ele. É a conservação da energia em versão térmica.",src:"Hewitt, §18.3"},
      {k:"Vale nos dois sentidos",h:"Trabalhar também aquece",p:"Esfregue as mãos ou use uma bomba de bicicleta: você <mark>realiza trabalho sobre o sistema</mark> e a energia interna sobe. Não é preciso adicionar calor.",src:"Hewitt, §18.3"},
      {k:"Adiabático",h:"Sem calor entrando ou saindo",p:"Basta isolar bem ou fazer o processo <mark>rápido demais</mark> para haver troca. Aí a variação de energia interna é exatamente o trabalho realizado.",src:"Hewitt, §18.4"},
      {k:"Consequência",h:"Comprimir aquece",p:"Comprimido, o gás recebe trabalho e <mark>esquenta</mark>; expandindo, ele realiza trabalho sobre a vizinhança e esfria. É a válvula do pneu que gela ao esvaziar.",src:"Hewitt, §18.4"},
      {k:"Meteorologia",h:"10 graus por quilômetro",p:"Uma parcela de ar seco que sobe expande e <mark>esfria cerca de 10 °C por km</mark>. A 25 °C no solo, chega a –35 °C se subir 6 km.",src:"Hewitt, §18.5"},
      {k:"Vento quente",h:"O chinuque",p:"Ar frio que <mark>desce das Montanhas Rochosas</mark> é comprimido e aquece muito. Por isso alguns vales tropicalizam em pleno inverno.",src:"Hewitt, §18.5"},
      {k:"Poluição presa",h:"Inversão de temperatura",p:"Quando o ar de cima está <mark>mais quente que o de baixo</mark>, a convecção para e os poluentes ficam aprisionados. É o que segura a smog de Los Angeles.",src:"Hewitt, §18.5"},
      {k:"Segunda lei",h:"O sentido dos processos",p:"O calor <mark>por si mesmo jamais flui do frio para o quente</mark>. Inverter isso exige realizar trabalho — é o que fazem geladeiras e bombas de calor.",src:"Hewitt, §18.6"},
      {k:"Implicação",h:"Energia sem gradiente é inútil",p:"A energia interna imensa do oceano <mark>não acende uma lâmpada</mark>: ela não flui espontaneamente para o filamento, que está mais quente.",src:"Hewitt, §18.6"},
      {k:"Máquina térmica",h:"Três etapas obrigatórias",p:"Recebe calor do reservatório quente, converte <mark>parte</mark> em trabalho e rejeita o resto num escoadouro frio. Vale para motor a vapor, a gasolina ou a jato.",src:"Hewitt, §18.6"},
      {k:"Carnot",h:"O teto do rendimento",p:"Rendimento ideal = <mark>(T quente − T fria) / T quente</mark>, com as temperaturas em kelvins. Entre 400 K e 300 K, o máximo possível é 25%.",src:"Hewitt, §18.6"},
      {k:"O que importa",h:"A diferença, não o atrito",p:"Mesmo <mark>sem atrito algum</mark>, parte do calor tem de ser rejeitada — é a segunda lei, não imperfeição mecânica. Daí superaquecer o vapor nas usinas.",src:"Hewitt, §18.6"},
      {k:"Caso-limite",h:"Sem gradiente, sem trabalho",p:"Se os dois reservatórios estão à mesma temperatura, (400 − 400)/400 = <mark>rendimento zero</mark>. Só um reservatório frio no zero absoluto daria 100%.",src:"Hewitt, §18.6"},
      {k:"Qualidade",h:"A ordem vira desordem",p:"A primeira lei cuida da quantidade de energia; a segunda, da <mark>qualidade</mark>. A cada transformação, a energia se dispersa em formas menos úteis.",src:"Hewitt, §18.7"},
      {k:"Veredito",h:"Moto-perpétuo é impossível",p:"As leis da termodinâmica <mark>destruíram o sonho</mark> do dispositivo que funcionaria indefinidamente sem receber mais energia. Não aposte contra elas.",src:"Hewitt, §18.1"},
      {q:true,k:"Questão de revisão",h:"Uma máquina térmica ideal opera entre reservatórios a 400 K e 300 K. Seu rendimento máximo é:",
        opts:[["A","100%, pois é ideal e não tem atrito"],["B","25%"],["C","75%"],["D","Depende do combustível utilizado"]],correct:1,
        explain:"Pela equação de Carnot, o rendimento ideal é (T quente − T fria)/T quente = (400 − 300)/400 = <b>25%</b>. Os outros 75% são necessariamente rejeitados — e isso não é culpa do atrito, é a segunda lei da termodinâmica."}
    ]
  },
